import { escapeHtml as e } from '../lib.mjs';

const image = (lead, index, alt, cls = '') => {
  const a = lead.assets?.[index];
  return a ? `<img class="${cls}" src="../../${e(a.path)}" alt="${e(alt)}" width="${a.width}" height="${a.height}" loading="lazy">` : '';
};
const button = label => `<button type="button" data-demo-contact>${e(label)} <span aria-hidden="true">↗</span></button>`;
const shell = (lead, type, links, body) => `<div class="pl pl-${type}" id="top"><header class="pl-header"><a class="pl-brand" href="#top">${e(lead.name)}</a><button type="button" class="pl-menu" data-menu-toggle aria-controls="site-nav" aria-expanded="false">Menü ☰</button><nav id="site-nav" aria-label="Hauptnavigation">${links.map(([name,id])=>`<a href="#${id}">${e(name)}</a>`).join('')}</nav></header><main>${body}</main><footer class="pl-footer"><span>${e(lead.name)} · ${e(lead.locality)}</span><a href="${e(lead.website)}" target="_blank" rel="noopener noreferrer">Original-Website ansehen ↗</a></footer></div>`;
const contact = (lead, title) => `<section class="pl-contact" id="kontakt"><div><span class="kicker">Kontakt</span><h2>${e(title)}</h2></div><div><p>${e(lead.name)}<br>${e(lead.locality)}<br>${e(lead.phone || '')}</p>${button('Kontakt aufnehmen')}</div></section>`;

function grossfeld(lead) {
 return shell(lead,'grossfeld',[['Fahrzeuge','fahrzeuge'],['Leistungen','leistungen'],['Kontakt','kontakt']],`
 <section class="gross-hero"><div class="gross-copy"><span class="kicker">Garage Grossfeld AG · Trimbach</span><h1>Unterwegs beginnt hier.</h1><p>Neu- und Gebrauchtwagen, Mietwagen und Dienstleistungen rund um Ihr Fahrzeug.</p><a class="text-link" href="#fahrzeuge">Fahrzeuge entdecken ↘</a></div><div class="gross-car">${image(lead,3,'DS N°8 aus dem Bildmaterial der Garage Grossfeld')}</div><small>DS N°8 / Bildmaterial der Originalwebsite</small></section>
 <section class="gross-brands" id="fahrzeuge"><span class="kicker">Markenwelt</span><div>Citroën <i>/</i> Honda <i>/</i> DS Automobiles <i>/</i> Mitsubishi</div><p>Auswahl an Neu- und Gebrauchtwagen</p></section>
 <section class="gross-services" id="leistungen"><div class="section-head"><span class="kicker">Bei Grossfeld</span><h2>Mehr als ein Fahrzeug.</h2></div><div class="gross-list"><article><h3>Verkauf</h3><p>Neu- und Gebrauchtwagen</p></article><article><h3>Mietwagen</h3><p>Mobilität für Ihre Pläne</p></article><article><h3>Werkstatt</h3><p>Service am Standort Trimbach</p></article></div></section>
 <section class="gross-feature">${image(lead,4,'Mitsubishi Outlander PHEV aus dem Bildmaterial der Garage Grossfeld')}<div><span class="kicker">In Trimbach</span><h2>Für jede Fahrt gut erreichbar.</h2><p>Einschlagweg 36<br>4632 Trimbach</p>${button('Kontakt zur Garage')}</div></section>${contact(lead,'Wir sind für Ihre Fragen da.')}`);
}

function wismer(lead) {
 return shell(lead,'wismer',[['Angebot','angebot'],['Besuch','besuch'],['Kontakt','kontakt']],`
 <section class="wis-hero"><div class="wis-top"><span>Blumengärtnerei Wismer AG</span><span>Zug / Floristik & Pflanzen</span></div><div class="wis-art"><span class="wis-ring" aria-hidden="true"></span><span class="wis-leaf" aria-hidden="true"></span><h1>Blumen.<br><em>Für das Leben.</em></h1><p>Sträusse, Arrangements und Pflanzen für unterschiedliche Anlässe und Räume.</p></div><a class="text-link" href="#angebot">Angebot entdecken ↘</a></section>
 <section class="wis-offer" id="angebot"><div><span class="kicker">Das Angebot</span><h2>Von der Geste bis zum Grün.</h2></div><div class="wis-list"><article><h3>Blumensträusse & Arrangements</h3><p>Für alle Anlässe</p></article><article><h3>Blumen Abos</h3><p>Wöchentlich oder monatlich</p></article><article><h3>Trauerfloristik & Grabbepflanzung</h3><p>Individuell gestaltet</p></article><article><h3>Balkon, Terrasse & Innenraum</h3><p>Standortgerechte Pflanzen und Innenbegrünung</p></article></div></section>
 <section class="wis-visit" id="besuch"><div class="wis-flower" aria-hidden="true"><span></span><span></span><span></span><span></span><span></span></div><div><span class="kicker">In Zug</span><h2>Ein Ort für Blumen und Pflanzen.</h2><p>Kirchmattstrasse 10<br>6300 Zug</p><p>Direkt unterhalb des Friedhofs. Kostenfreie Parkplätze befinden sich vor der Tür.</p>${button('Kontakt anfragen')}</div></section>${contact(lead,'Blumen verbinden.')}`);
}

function seiler(lead) {
 const cats=[['Holzkochherde','Heizen & Kochen'],['Elektrowerkzeuge','Für Werkstatt & Baustelle'],['Pumpen','Für Haus & Garten'],['Schliesstechnik','Für sichere Zugänge'],['Briefkästen & Tresore','Für Gebäude & Werte'],['Drechselbänke & Schnitzwerkzeuge','Für die Holzarbeit']];
 return shell(lead,'seiler',[['Sortiment','sortiment'],['Fachgeschäft','fachgeschaeft'],['Kontakt','kontakt']],`
 <section class="sei-hero"><div class="sei-top"><span>BURGDORF / SEIT 1948</span><span>Qualität · Beratung · Service</span></div><div class="sei-copy"><span class="kicker">E. Seiler AG</span><h1>Das Richtige<br>für die Arbeit.</h1><p>Elektrowerkzeuge, Holzkochherde und Schliesstechnik. Im Fachgeschäft an der Hohengasse in Burgdorf.</p><a class="text-link" href="#sortiment">Sortiment ansehen ↘</a></div><div class="sei-photo">${image(lead,0,'Elektrowerkzeuge aus dem Bildmaterial der E. Seiler AG')}</div></section>
 <section class="sei-index" id="sortiment"><div class="section-head"><span class="kicker">Sortiment / Auswahl</span><h2>Wofür suchen Sie eine Lösung?</h2></div><div class="sei-grid">${cats.map(([name,desc])=>`<article><h3>${e(name)}</h3><p>${e(desc)}</p></article>`).join('')}</div></section>
 <section class="sei-store" id="fachgeschaeft">${image(lead,1,'Holzkochherd aus dem Bildmaterial der E. Seiler AG')}<div><span class="kicker">Vor Ort in Burgdorf</span><h2>Fachwissen gehört dazu.</h2><p>Das Geschäft der E. Seiler AG befindet sich an der Hohengasse 31 in Burgdorf. Das Sortiment reicht von Holzkochherden über Elektrowerkzeuge und Pumpen bis zur Schliesstechnik.</p>${button('Kontakt zum Fachgeschäft')}</div></section>${contact(lead,'Fragen zum Sortiment?')}`);
}

function graf(lead) {
 return shell(lead,'graf',[['Gartenbau','gartenbau'],['Einblicke','einblicke'],['Kontakt','kontakt']],`
 <section class="graf-hero"><div><span class="kicker">Martin Graf Gartenbau GmbH · Lindau</span><h1>Wo Natur<br>Raum bekommt.</h1><p>Gärten, Grünanlagen, Balkone und Terrassen – mit persönlicher Beratung und naturnaher Gestaltung.</p><a class="text-link" href="#gartenbau">Mehr erfahren ↘</a></div><figure>${image(lead,1,'Botanische Nahaufnahme aus dem Bildmaterial von Martin Graf Gartenbau')}</figure></section>
 <section class="graf-quote" id="gartenbau"><span class="kicker">Unsere Haltung</span><p>«Qualität, Zuverlässigkeit und eine naturnahe Gestaltung»</p><small>Das ist der Anspruch, den Martin Graf Gartenbau für die Arbeit draussen formuliert.</small></section>
 <section class="graf-fields" id="einblicke"><div><span class="kicker">Arbeitsfelder</span><h2>Vom Garten bis zur Terrasse.</h2></div><div><p> Gärten</p><p> Grünanlagen</p><p> Balkone & Terrassen</p></div></section>
 <section class="graf-strip">${image(lead,2,'Blütenaufnahme aus dem Bildmaterial von Martin Graf Gartenbau')}<div><span class="kicker">Persönlich</span><p>Das Unternehmen legt Wert auf Beratungsgespräche vor Ort und bezieht die Ideen der Kundschaft in die Arbeit ein.</p>${button('Kontakt anfragen')}</div></section>${contact(lead,'Raum für Ihre Ideen.')}`);
}

function lantii(lead) {
 return shell(lead,'lantii',[['Leistungen','leistungen'],['Bilder','bilder'],['Kontakt','kontakt']],`
 <section class="lan-hero"><div class="lan-top"><span>GIPSER / MALER / FASSADENISOLATION</span><span>VILLIGEN AG</span></div><h1>Oberflächen<br>machen Räume.</h1><div class="lan-bottom"><p>Lantii GmbH verbindet Gipser- und Malerarbeiten mit Fassadenisolation.</p><a class="text-link" href="#leistungen">Leistungen ansehen ↘</a></div><div class="lan-block" aria-hidden="true"></div></section>
 <section class="lan-work" id="leistungen"><div class="section-head"><span class="kicker">Arbeitsfelder</span><h2>Von innen nach aussen.</h2></div><div class="lan-grid"><article><h3>Gipserarbeiten</h3></article><article><h3>Malerarbeiten</h3></article><article><h3>Fassadenisolation</h3></article></div></section>
 <section class="lan-pictures" id="bilder"><div class="lan-picture-head"><span class="kicker">Einblicke</span><h2>Gebäude und Fassaden.</h2><p>Einblicke in unterschiedliche Bauphasen.</p></div><div class="lan-photos"><figure>${image(lead,1,'Gebäudeaufnahme von der Originalwebsite der Lantii GmbH')}<figcaption>Bildmaterial / Lantii GmbH</figcaption></figure><figure>${image(lead,2,'Baustellenaufnahme von der Originalwebsite der Lantii GmbH')}<figcaption>Bildmaterial / Lantii GmbH</figcaption></figure></div></section>${contact(lead,'Sprechen wir über Ihr Vorhaben.')}`);
}

export function render(lead) {
 const pages={grossfeld,wismer,seiler,'martin-graf-gartenbau':graf,lantii};
 if(!pages[lead.slug]) throw new Error(`Unsupported places slug: ${lead.slug}`);
 return {html:pages[lead.slug](lead),css};
}

const css = `
.pl{--ink:#18201d;--paper:#f7f5f0;--accent:#203e36;color:var(--ink);background:var(--paper);font-family:'DM Sans',Arial,sans-serif;min-width:0}.pl *{box-sizing:border-box}.pl img{display:block;max-width:100%}.pl a{color:inherit}.pl button{font:inherit;cursor:pointer}.pl a:focus-visible,.pl button:focus-visible{outline:3px solid #d96b3f;outline-offset:4px}.pl-header{position:relative;z-index:5;display:flex;align-items:center;justify-content:space-between;gap:2rem;padding:19px clamp(20px,4.5vw,76px);border-bottom:1px solid currentColor}.pl-brand{text-decoration:none;font-weight:800;font-size:clamp(16px,1.65vw,24px);line-height:1.05;max-width:260px}.pl-header nav{display:flex;align-items:center;gap:clamp(16px,2.5vw,38px)}.pl-header nav a{text-decoration:none;font-size:13px;font-weight:700}.pl-header nav a:hover,.pl-footer a:hover{text-decoration:underline;text-underline-offset:5px}.pl-menu{display:none;color:inherit;background:transparent;border:1px solid currentColor;padding:9px 13px}.pl main{display:block}.pl h1,.pl h2,.pl h3,.pl p{margin-top:0}.pl .kicker{font-size:11px;letter-spacing:.15em;text-transform:uppercase;font-weight:800}.pl .text-link{display:inline-flex;align-items:center;font-size:13px;font-weight:800;text-decoration:none;border-bottom:1px solid currentColor;padding-bottom:9px}.pl-contact{display:grid;grid-template-columns:1.4fr 1fr;gap:30px;align-items:end;padding:clamp(45px,6vw,100px) clamp(20px,5vw,80px);background:var(--accent);color:#fff}.pl-contact h2{font-size:clamp(36px,5vw,74px);letter-spacing:-.055em;line-height:.95;margin:25px 0 0;max-width:700px}.pl-contact p{line-height:1.7}.pl button[data-demo-contact]{border:1px solid currentColor;background:transparent;color:inherit;padding:14px 18px;font-size:13px;font-weight:800;display:inline-flex;justify-content:space-between;gap:32px;min-width:190px}.pl button[data-demo-contact]:hover{background:var(--ink);color:#fff}.pl-footer{display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap;padding:24px clamp(20px,5vw,80px);font-size:12px}.pl-footer a{text-decoration:none}.pl section[id]{scroll-margin-top:60px}
.pl-grossfeld{--paper:#f0eee9;--ink:#172226;--accent:#172226;font-family:'Satoshi','DM Sans',sans-serif}.gross-hero{position:relative;min-height:660px;overflow:hidden;background:#e9e7e1}.gross-copy{position:relative;z-index:2;padding:clamp(52px,6vw,90px) 5vw 0;max-width:900px}.gross-copy h1{font-family:'Clash Display','Satoshi',sans-serif;font-size:clamp(52px,8vw,132px);line-height:.89;letter-spacing:-.035em;max-width:760px;margin:24px 0}.gross-copy p{max-width:380px;font-size:17px;line-height:1.5}.gross-car{position:absolute;inset:auto 0 0;height:55%;overflow:hidden}.gross-car img{width:100%;height:100%;object-fit:cover;object-position:center 43%}.gross-hero small{position:absolute;right:5vw;bottom:19px;color:#fff;font-size:10px;letter-spacing:.12em;text-transform:uppercase;text-shadow:0 1px 3px #111}.gross-brands{padding:35px 5vw 45px;background:#142126;color:#fff}.gross-brands>div{font-family:'Barlow Condensed',sans-serif;text-transform:uppercase;font-size:clamp(29px,4.8vw,72px);line-height:1.08;margin:18px 0 10px}.gross-brands i{font-style:normal;color:#cf634a}.gross-brands p{font-size:12px;margin:0}.gross-services{padding:90px 5vw}.gross-services .section-head{display:flex;gap:40px;align-items:baseline;justify-content:space-between}.gross-services h2{font-size:clamp(36px,5vw,74px);letter-spacing:-.06em;margin:0 0 48px}.gross-list{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid #9da9a6}.gross-list article{padding:28px 24px 38px 0;border-bottom:1px solid #9da9a6}.gross-list b{font-size:11px}.gross-list h3{font-size:clamp(25px,3vw,45px);letter-spacing:-.05em;margin:45px 0 8px}.gross-list p{font-size:14px;color:#53615e}.gross-feature{display:grid;grid-template-columns:1.35fr 1fr;min-height:390px;background:#c9d4d5}.gross-feature img{width:100%;height:100%;object-fit:cover}.gross-feature>div{padding:60px 8%;align-self:center}.gross-feature h2{font-size:clamp(36px,4vw,58px);line-height:1;letter-spacing:-.05em;margin:26px 0}.gross-feature p{line-height:1.6}
.pl-wismer{--paper:#f4dcc4;--ink:#512c38;--accent:#512c38;font-family:'Satoshi','DM Sans',sans-serif}.wis-hero{padding:26px 5vw 50px;min-height:690px;background:#ee88a1;overflow:hidden;position:relative}.wis-top{display:flex;justify-content:space-between;gap:20px;font-size:11px;text-transform:uppercase;font-weight:800;letter-spacing:.13em}.wis-art{position:relative;min-height:540px;display:flex;align-items:center}.wis-art h1{position:relative;z-index:2;font-family:'Cormorant Garamond',Georgia,serif;font-weight:600;font-size:clamp(70px,13vw,210px);letter-spacing:-.065em;line-height:.77;margin:30px 0}.wis-art em{font-weight:400}.wis-art p{position:absolute;z-index:2;right:0;bottom:70px;width:260px;line-height:1.5;font-size:16px}.wis-ring{position:absolute;border:32px solid #a33b5c;border-radius:50%;width:clamp(300px,43vw,670px);aspect-ratio:1;right:7%;top:0;transform:rotate(-24deg) scaleX(.8)}.wis-leaf{position:absolute;background:#2c533e;width:130px;height:320px;border-radius:100% 0 100% 0;right:23%;top:50px;transform:rotate(28deg)}.wis-offer{display:grid;grid-template-columns:.8fr 1.2fr;gap:8vw;padding:110px 5vw}.wis-offer h2,.wis-visit h2{font-family:'Cormorant Garamond',Georgia,serif;font-size:clamp(48px,5.7vw,86px);line-height:.95;letter-spacing:-.04em;margin:25px 0}.wis-list article{border-top:1px solid #a78379;padding:18px 0 24px;display:block}.wis-list article:last-child{border-bottom:1px solid #a78379}.wis-list span{font-size:12px}.wis-list h3{font-size:clamp(19px,2vw,30px);letter-spacing:-.035em;margin:0}.wis-list p{font-size:13px;margin:5px 0 0}.wis-visit{display:grid;grid-template-columns:1fr 1fr;gap:5vw;align-items:center;background:#b9cfad;padding:70px 8vw;min-height:530px}.wis-visit p{max-width:380px;line-height:1.55}.wis-flower{position:relative;height:340px;width:340px;max-width:100%;margin:auto}.wis-flower span{position:absolute;width:130px;height:185px;background:#e96d87;border-radius:85% 15% 85% 15%;left:100px;top:55px;transform-origin:70px 130px}.wis-flower span:nth-child(1){transform:rotate(0deg)}.wis-flower span:nth-child(2){transform:rotate(72deg)}.wis-flower span:nth-child(3){transform:rotate(144deg)}.wis-flower span:nth-child(4){transform:rotate(216deg)}.wis-flower span:nth-child(5){transform:rotate(288deg)}.wis-flower:after{content:'';position:absolute;z-index:2;width:76px;height:76px;left:127px;top:137px;border-radius:50%;background:#b2465f}
.pl-seiler{--paper:#edece7;--ink:#142629;--accent:#142629;font-family:'Switzer','DM Sans',sans-serif}.pl-seiler .pl-header{background:#142629;color:#fff}.sei-hero{position:relative;min-height:570px;background:#d9dacc;overflow:hidden}.sei-top{display:flex;justify-content:space-between;gap:20px;padding:17px 5vw;border-bottom:1px solid #879693;font-size:10px;letter-spacing:.15em;font-weight:800}.sei-copy{position:relative;z-index:2;padding:64px 5vw 70px;max-width:650px}.sei-copy h1,.sei-index h2,.sei-store h2{font-family:'Barlow Condensed',sans-serif;text-transform:uppercase;line-height:.8;letter-spacing:-.025em}.sei-copy h1{font-size:clamp(70px,8vw,130px);margin:26px 0 38px}.sei-copy p{max-width:350px;line-height:1.5}.sei-photo{position:absolute;right:0;top:51px;bottom:0;width:49%;overflow:hidden}.sei-photo:before{content:'';position:absolute;inset:0;background:linear-gradient(90deg,#d9dacc 0%,transparent 30%);z-index:1}.sei-photo img{width:100%;height:100%;object-fit:cover}.sei-index{padding:85px 5vw;background:#f1f0eb}.sei-index .section-head{display:flex;justify-content:space-between;gap:30px;align-items:end;margin-bottom:30px}.sei-index h2{font-size:clamp(44px,5vw,76px);max-width:600px;margin:0}.sei-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;background:#a3ada8;border:1px solid #a3ada8}.sei-grid article{background:#f1f0eb;padding:24px;min-height:210px;display:flex;flex-direction:column}.sei-grid span{font-size:12px;font-weight:800}.sei-grid h3{font-family:'Barlow Condensed',sans-serif;text-transform:uppercase;font-size:clamp(30px,3vw,47px);line-height:.95;margin:auto 0 10px}.sei-grid p{font-size:12px;margin:0}.sei-store{display:grid;grid-template-columns:1fr 1fr;min-height:430px;background:#d8dfda}.sei-store img{width:100%;height:100%;object-fit:cover}.sei-store>div{padding:65px 9%;align-self:center}.sei-store h2{font-size:clamp(46px,5vw,75px);margin:26px 0}.sei-store p{line-height:1.6;max-width:470px}
.pl-graf{--paper:#f5f4ec;--ink:#173c30;--accent:#20483b;font-family:'Satoshi','DM Sans',sans-serif}.graf-hero{padding:85px 5vw 0}.graf-hero>div{max-width:880px}.graf-hero h1{font-family:'Cormorant Garamond',Georgia,serif;font-size:clamp(72px,10vw,158px);font-weight:500;line-height:.82;letter-spacing:-.055em;margin:30px 0}.graf-hero p{max-width:500px;font-size:18px;line-height:1.5;margin:0 0 30px}.graf-hero figure{height:clamp(190px,27vw,350px);margin:80px -5vw 0;overflow:hidden}.graf-hero img{width:100%;height:100%;object-fit:cover;object-position:left center}.graf-quote{text-align:center;padding:105px 8vw;max-width:1060px;margin:auto}.graf-quote p{font-family:'Cormorant Garamond',Georgia,serif;font-size:clamp(44px,5.6vw,80px);line-height:.98;margin:30px 0}.graf-quote small{font-size:14px}.graf-fields{padding:75px 5vw;display:grid;grid-template-columns:1fr 1fr;gap:8vw;background:#d8dfce}.graf-fields h2{font-family:'Cormorant Garamond',Georgia,serif;font-size:clamp(50px,5.5vw,85px);line-height:.95;margin:25px 0}.graf-fields p{border-top:1px solid #719082;display:flex;gap:26px;align-items:baseline;padding:24px 0;margin:0;font-size:clamp(24px,2.6vw,36px)}.graf-fields p:last-child{border-bottom:1px solid #719082}.graf-fields p span{font-size:12px}.graf-strip{display:grid;grid-template-columns:1fr 1fr;min-height:360px}.graf-strip img{width:100%;height:100%;object-fit:cover;object-position:left center}.graf-strip>div{padding:60px 10%;align-self:center}.graf-strip p{font-family:'Cormorant Garamond',Georgia,serif;font-size:clamp(29px,3.2vw,48px);line-height:1.05;margin:24px 0}
.pl-lantii{--paper:#e9e7df;--ink:#1a2d36;--accent:#1a2d36;font-family:'Switzer','DM Sans',sans-serif}.lan-hero{position:relative;min-height:620px;padding:22px 5vw 70px;background:#dc5537;color:#101414;overflow:hidden}.lan-top{display:flex;justify-content:space-between;gap:20px;padding-bottom:20px;border-bottom:1px solid #8c3e31;font-size:10px;letter-spacing:.14em;font-weight:800}.lan-hero h1{position:relative;z-index:2;font-family:'Clash Display','Switzer',sans-serif;font-size:clamp(67px,10vw,160px);line-height:.83;letter-spacing:-.03em;margin:105px 0 65px;max-width:1200px}.lan-bottom{position:relative;z-index:2;display:flex;justify-content:space-between;align-items:end;gap:30px}.lan-bottom p{font-size:18px;max-width:380px;line-height:1.4;margin:0}.lan-block{position:absolute;right:8%;top:19%;width:35%;height:57%;background:#f5bda2;transform:skewY(-9deg)}.lan-work{padding:95px 5vw}.lan-work .section-head{display:flex;justify-content:space-between;gap:30px;align-items:end}.lan-work h2{font-size:clamp(42px,5vw,78px);line-height:.95;letter-spacing:-.06em;max-width:700px}.lan-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.lan-grid article{min-height:250px;padding:24px;background:#1a2d36;color:#fff;display:flex;flex-direction:column;justify-content:space-between}.lan-grid article:nth-child(2){background:#aac0b8;color:#1a2d36}.lan-grid article:nth-child(3){background:#d47351;color:#1a2d36}.lan-grid span{font-size:12px}.lan-grid h3{font-size:clamp(30px,3vw,48px);line-height:.95;letter-spacing:-.045em;margin:0;overflow-wrap:anywhere}.lan-pictures{padding:90px 5vw;background:#d4dcd6}.lan-picture-head{display:grid;grid-template-columns:.55fr 1fr .7fr;gap:20px;align-items:end;margin-bottom:40px}.lan-picture-head h2{font-size:clamp(38px,4.5vw,69px);letter-spacing:-.06em;line-height:.95;margin:0}.lan-picture-head p{font-size:13px;line-height:1.5;max-width:260px}.lan-photos{display:grid;grid-template-columns:1.3fr .7fr;gap:20px}.lan-photos figure{margin:0}.lan-photos img{height:clamp(250px,32vw,470px);width:100%;object-fit:cover}.lan-photos figcaption{font-size:10px;text-transform:uppercase;letter-spacing:.12em;margin-top:10px}
@media(max-width:800px){.pl-header{flex-wrap:wrap;gap:10px}.pl-menu{display:block}.pl-header nav{display:none;width:100%;flex-basis:100%;flex-direction:column;align-items:stretch;gap:0;padding:8px 0}.pl-header nav.open{display:flex}.pl-header nav a{padding:12px 3px;border-top:1px solid currentColor}.gross-hero{min-height:590px}.gross-car{height:48%}.gross-services .section-head,.sei-index .section-head,.lan-work .section-head{display:block}.wis-art p{bottom:15px;right:0}.wis-ring{right:-10%}.sei-photo{width:55%;opacity:.7}.sei-copy{max-width:560px}.sei-grid{grid-template-columns:repeat(2,1fr)}.lan-picture-head{grid-template-columns:1fr 1fr}.lan-picture-head .kicker{grid-column:1/-1}}
@media(max-width:600px){.pl-contact{grid-template-columns:1fr}.pl-contact h2{margin:18px 0 8px}.pl-footer{display:block}.pl-footer a{display:block;margin-top:9px}.gross-hero{min-height:590px}.gross-copy{padding:50px 20px 0}.gross-copy h1{font-size:clamp(55px,14vw,85px)}.gross-copy p{font-size:15px;max-width:290px}.gross-car{height:42%}.gross-brands,.gross-services{padding-left:20px;padding-right:20px}.gross-brands>div{font-size:35px}.gross-services{padding-top:65px;padding-bottom:65px}.gross-list{grid-template-columns:1fr}.gross-list h3{margin:18px 0 8px}.gross-feature{grid-template-columns:1fr}.gross-feature img{height:240px}.gross-feature>div{padding:40px 20px}.wis-hero{padding:20px;min-height:630px}.wis-top{display:block;line-height:1.7}.wis-top span{display:block}.wis-art{min-height:520px;align-items:flex-start}.wis-art h1{font-size:clamp(65px,17vw,100px);line-height:.85;margin-top:130px}.wis-ring{width:360px;right:-130px;top:30px;border-width:20px}.wis-leaf{width:80px;height:200px;right:10px;top:55px}.wis-art p{left:0;bottom:17px;font-size:14px}.wis-offer{display:block;padding:70px 20px}.wis-offer h2{margin-bottom:45px}.wis-visit{display:block;padding:55px 20px}.wis-flower{transform:scale(.7);margin:-40px auto}.sei-hero{min-height:640px}.sei-top{padding:15px 20px}.sei-top span:last-child{display:none}.sei-copy{padding:40px 20px}.sei-copy h1{font-size:80px}.sei-photo{top:auto;width:100%;height:205px;opacity:1}.sei-photo:before{background:linear-gradient(#d9dacc,transparent 30%)}.sei-index{padding:65px 20px}.sei-grid{grid-template-columns:1fr}.sei-grid article{min-height:145px}.sei-grid h3{margin:20px 0 8px}.sei-store{grid-template-columns:1fr}.sei-store img{height:230px}.sei-store>div{padding:45px 20px}.graf-hero{padding:70px 20px 0}.graf-hero h1{font-size:clamp(75px,18vw,115px)}.graf-hero p{font-size:16px}.graf-hero figure{margin:60px -20px 0;height:230px}.graf-quote{padding:75px 20px}.graf-fields{display:block;padding:65px 20px}.graf-fields>div:last-child{margin-top:45px}.graf-strip{grid-template-columns:1fr}.graf-strip img{height:230px}.graf-strip>div{padding:55px 20px}.lan-hero{min-height:620px;padding:20px}.lan-top span:last-child{display:none}.lan-hero h1{font-size:clamp(50px,13vw,80px);margin:145px 0 60px}.lan-bottom{display:block}.lan-bottom p{font-size:16px;margin-bottom:25px}.lan-block{width:60%;height:32%;right:0;top:15%}.lan-work{padding:70px 20px}.lan-grid{grid-template-columns:1fr}.lan-grid article{min-height:145px}.lan-pictures{padding:70px 20px}.lan-picture-head{display:block}.lan-picture-head h2{margin:18px 0}.lan-photos{grid-template-columns:1fr}.lan-photos img{height:250px}}
.pl-seiler .pl-menu{color:#fff}.gross-hero{display:flex;flex-direction:column;min-height:0}.gross-copy{padding-bottom:55px}.gross-car{position:relative;inset:auto;height:350px;flex:none}.gross-hero small{bottom:17px}.pl-graf .graf-hero figure{width:auto}@media(max-width:900px){.lan-grid{grid-template-columns:1fr}.lan-grid article{min-height:150px}}@media(max-width:600px){.sei-hero{min-height:690px}.pl-graf .pl-brand{max-width:210px}.wis-leaf{right:-25px;top:25px}.gross-car{height:260px}}@media(max-width:800px){.sei-hero{display:flex;flex-direction:column;min-height:0}.sei-copy{max-width:none;padding-bottom:42px}.sei-photo{position:relative;inset:auto;width:100%;height:230px;opacity:1}.sei-photo:before{background:none}}@media(prefers-reduced-motion:reduce){.pl *{scroll-behavior:auto!important;animation:none!important;transition:none!important}}
`;
