import { escapeHtml as e } from '../lib.mjs';

const image = (lead, needle, className = '') => {
  const item = (lead.assets || []).find(asset => `${asset.url || ''} ${asset.alt || ''}`.toLowerCase().includes(needle.toLowerCase()));
  if (!item) return '';
  return `<img class="${className}" src="../../${e(item.path)}" alt="${e(item.alt || lead.name)}" loading="lazy" decoding="async" width="${Number(item.width) || 800}" height="${Number(item.height) || 600}">`;
};

const contact = (label = 'Kontakt aufnehmen') => `<button class="sd-button" type="button" data-demo-contact>${label}</button>`;
const source = lead => `<a class="sd-source" href="${e(lead.website)}" target="_blank" rel="noopener noreferrer">Original-Website ansehen ↗</a>`;
const header = (lead, links, label = 'Kontakt aufnehmen') => `<header class="sd-header"><a class="sd-brand" href="#start" aria-label="${e(lead.name)}: zum Anfang">${e(lead.name)}</a><button class="sd-menu" type="button" data-menu-toggle aria-controls="site-nav" aria-expanded="false">Menü</button><nav id="site-nav" class="sd-nav" aria-label="Hauptnavigation">${links.map(([text, target]) => `<a href="#${target}">${text}</a>`).join('')}${contact(label)}</nav></header>`;
const footer = (lead, address) => `<footer class="sd-footer"><strong>${e(lead.name)}</strong><span>${e(address)}</span><span>${e(lead.phone)}</span>${source(lead)}</footer>`;

function sopra(lead) {
  const facade = image(lead, 'af4e4688', 'sd-hero-photo');
  const portrait = image(lead, 'Veprim', 'sd-portrait');
  const html = `<div class="sd-site sd-sopra" id="start">
    ${header(lead, [['Küche','kueche'],['Über uns','ueber-uns'],['Besuch','besuch']], 'Anfragen')}
    <main>
      <section class="sd-sopra-hero" aria-labelledby="sopra-title"><div class="sd-sopra-intro"><span class="sd-kicker">Restaurant · Attelwil</span><h1 id="sopra-title">Zeit für<br><em>gutes Essen.</em></h1><p>Mediterrane, italienische und Schweizer Küche an der Hauptstrasse 56.</p><div class="sd-actions">${contact('Anfragen')}<a class="sd-text-link" href="#kueche">Küche entdecken ↓</a></div></div><div class="sd-sopra-image">${facade || '<span class="sd-sopra-type" aria-hidden="true">SOPRA</span>'}<span class="sd-image-caption">5056 Attelwil</span></div></section>
      <section class="sd-sopra-food sd-section" id="kueche"><div class="sd-section-head"><span class="sd-kicker">01 / Küche</span><h2>Zum Essen<br>und Sein.</h2></div><div class="sd-section-body"><p>Veprim Ukaj beschreibt seine Küche als mediterran, italienisch und schweizerisch. Auch Takeaway gehört zum Angebot.</p><div class="sd-offer-line"><span>Im Restaurant</span><strong>Gemeinsam geniessen</strong></div><div class="sd-offer-line"><span>Für unterwegs</span><strong>Takeaway</strong></div></div></section>
      <section class="sd-sopra-about sd-section" id="ueber-uns"><div class="sd-about-image">${portrait || '<span aria-hidden="true">S</span>'}</div><div><span class="sd-kicker">02 / Gastgeber</span><h2>Leidenschaft<br>fürs Kochen.</h2><p>Veprim Ukaj ist Geschäftsführer und Koch des Restaurant Sopra. Hier bringt er seine langjährige Erfahrung in der Gastronomie ein.</p></div></section>
      <section class="sd-sopra-visit sd-section" id="besuch"><div><span class="sd-kicker">03 / Besuch</span><h2>Wir freuen uns<br>auf Sie.</h2><p>Hauptstrasse 56<br>5056 Attelwil</p>${contact('Anfragen')}</div><div class="sd-hours"><h3>Öffnungszeiten</h3><p>Montag & Dienstag <b>Ruhetag</b></p><p>Mittwoch bis Freitag <b>09:00–14:00 / 17:00–23:00</b></p><p>Samstag <b>09:00–23:00</b></p><p>Sonntag <b>09:30–22:00</b></p><small>Telefon ${e(lead.phone)}</small></div></section>
    </main>${footer(lead, 'Hauptstrasse 56, 5056 Attelwil')}</div>`;
  return { html, css: css };
}

function wacker(lead) {
  const terrace = image(lead, '6116e83d', 'sd-hero-photo');
  const food = image(lead, 'b216b588', 'sd-food-photo');
  const html = `<div class="sd-site sd-wacker" id="start">
    ${header(lead, [['Genuss','genuss'],['Mittag','mittag'],['Besuch','besuch']], 'Reservierung anfragen')}
    <main>
      <section class="sd-wacker-hero" aria-labelledby="wacker-title"><div class="sd-wacker-photo">${terrace || '<span aria-hidden="true">WACKER</span>'}</div><div class="sd-wacker-title"><span class="sd-kicker">Reinach BL · Restaurant</span><h1 id="wacker-title">Ein guter<br>Grund, <i>zu bleiben.</i></h1><p>Französischer Genuss, saisonale Küche und Zeit am Tisch.</p><p class="sd-date-note"><strong>Betriebsferien:</strong> 21. September bis und mit 12. Oktober 2026.</p>${contact('Reservierung anfragen')}</div></section>
      <section class="sd-wacker-menu sd-section" id="genuss"><div><span class="sd-kicker">Die Küche</span><h2>Für den Moment<br>am Tisch.</h2></div><div><p>Saisonale Köstlichkeiten und Klassiker stehen auf der Karte. Dazu gibt es Weine im Offenausschank und als Flaschen.</p><ul class="sd-wacker-list"><li><span>01</span> Saisonale Küche</li><li><span>02</span> Klassiker</li><li><span>03</span> Weine</li></ul></div></section>
      <section class="sd-wacker-lunch sd-section" id="mittag"><div class="sd-lunch-copy"><span class="sd-kicker">Mittags im Wacker</span><h2>Pause mit<br>Geschmack.</h2><p>Wochenmenü und Business Lunch geben dem Mittag eine klare Adresse in Reinach.</p><a class="sd-text-link" href="#besuch">Besuch planen ↗</a></div><div class="sd-lunch-image">${food || '<span aria-hidden="true">W</span>'}</div></section>
      <section class="sd-wacker-charbonnade sd-section"><span class="sd-kicker">Auch am Abend</span><h2>Charbonnade<br><i>à discrétion.</i></h2><p>Ein Angebot für Montag- und Mittwochabend, direkt aus der bestehenden Wacker-Karte.</p></section>
      <section class="sd-wacker-visit sd-section" id="besuch"><div><span class="sd-kicker">Zu Besuch</span><h2>Wir sehen uns<br>in Reinach.</h2><p>Fleischbachstrasse 25<br>4153 Reinach</p><p class="sd-date-note"><strong>Betriebsferien:</strong> 21. September bis und mit 12. Oktober 2026.</p>${contact('Reservierung anfragen')}</div><div class="sd-hours"><h3>Reguläre Öffnungszeiten</h3><p>Montag bis Samstag <b>11:00–23:00</b></p><p>Sonntag <b>11:00–22:00</b></p><small>Telefon ${e(lead.phone)}</small></div></section>
    </main>${footer(lead, 'Fleischbachstrasse 25, 4153 Reinach')}</div>`;
  return { html, css };
}

function lanz(lead) {
  const html = `<div class="sd-site sd-lanz" id="start">
    ${header(lead, [['Salon','salon'],['Standort','standort'],['Kontakt','kontakt']], 'Termin anfragen')}
    <main>
      <section class="sd-lanz-hero"><span class="sd-kicker">Coiffeur in Bleienbach</span><h1>Coiffeur<br><span>Lanz.</span></h1><div class="sd-lanz-hero-bottom"><p>Vreni Lanz<br>Eichi 20, 3368 Bleienbach</p>${contact('Termin anfragen')}</div></section>
      <section class="sd-lanz-line sd-section" id="salon"><span class="sd-kicker">01 / Willkommen</span><h2>Ein Salon.<br>Eine klare Adresse.</h2><p>Coiffeur Lanz von Vreni Lanz in Bleienbach. Für Fragen und Termine erreichen Sie den Salon direkt über die angegebenen Kontaktdaten.</p></section>
      <section class="sd-lanz-location sd-section" id="standort"><span class="sd-kicker">02 / Besuch</span><div><h2>Hier finden<br>Sie uns.</h2><address>Eichi 20<br>3368 Bleienbach</address></div><span class="sd-lanz-stamp">BL<br>BE</span></section>
      <section class="sd-lanz-contact sd-section" id="kontakt"><span class="sd-kicker">03 / Kontakt</span><h2>Ein Anruf<br>genügt.</h2><p>Telefon ${e(lead.phone)}<br>Mobil 079 713 62 32<br>info@coiffeurlanz.ch</p>${contact('Termin anfragen')}</section>
    </main>${footer(lead, 'Eichi 20, 3368 Bleienbach')}</div>`;
  return { html, css };
}

function hairstudio(lead) {
  const html = `<div class="sd-site sd-hairstudio" id="start">
    ${header(lead, [['Leistungen','leistungen'],['Salon','salon'],['Besuch','besuch']], 'Termin anfragen')}
    <main>
      <section class="sd-hairstudio-hero"><div><span class="sd-kicker">Fehraltorf · Hairstudio F</span><h1>Cut.<br>Colors.<br><em>More.</em></h1><p>Haare, Farbe und Styling an der Bahnhofstrasse 12.</p>${contact('Termin anfragen')}<p class="sd-date-note"><strong>Ferien:</strong> 24. bis und mit 26. September 2026. Ab 28. September wieder da.</p></div><div class="sd-hairstudio-hero-side"><span>F</span><p>Hairstudio<br>Fehraltorf</p></div></section>
      <section class="sd-hairstudio-services sd-section" id="leistungen"><span class="sd-kicker">01 / Leistungen</span><h2>Ihr Look.<br>Ihre Wahl.</h2><div class="sd-service-list"><div><span>01</span><strong>Waschen, schneiden, föhnen</strong></div><div><span>02</span><strong>Färben & Tönen</strong></div><div><span>03</span><strong>Mèches & Dauerwelle</strong></div><div><span>04</span><strong>Augenbrauen & Wimpern</strong></div></div></section>
      <section class="sd-hairstudio-about sd-section" id="salon"><span class="sd-kicker">02 / Salon</span><h2>Klein, fein<br>und persönlich.</h2><p>Fiorina Provenzano begrüsst Sie im Hairstudio F. Der Salon ist rollstuhlgängig; ein Kundenparkplatz befindet sich vor dem Haus.</p></section>
      <section class="sd-hairstudio-visit sd-section" id="besuch"><div><span class="sd-kicker">03 / Besuch</span><h2>Bis bald in<br>Fehraltorf.</h2><p>Bahnhofstrasse 12<br>8320 Fehraltorf</p><p class="sd-date-note"><strong>Ferien:</strong> 24. bis und mit 26. September 2026.</p>${contact('Termin anfragen')}</div><div class="sd-hours"><h3>Reguläre Öffnungszeiten</h3><p>Montag & Dienstag <b>08:30–12:00 / 13:30–18:00</b></p><p>Mittwoch <b>geschlossen</b></p><p>Donnerstag & Freitag <b>08:30–12:00 / 13:30–18:30</b></p><p>Samstag <b>08:00–13:00</b></p><small>Telefon ${e(lead.phone)}</small></div></section>
    </main>${footer(lead, 'Bahnhofstrasse 12, 8320 Fehraltorf')}</div>`;
  return { html, css };
}

function holiday(lead) {
  const salonImage = image(lead, 'PosterMyWall-4', 'sd-hero-photo');
  const html = `<div class="sd-site sd-holiday" id="start">
    ${header(lead, [['Salon','salon'],['Besuch','besuch'],['Kontakt','kontakt']], 'Termin anfragen')}
    <main>
      <section class="sd-holiday-hero"><div class="sd-holiday-title"><span class="sd-kicker">Wangen an der Aare</span><h1>Coiffeur<br><i>Holiday.</i></h1><p>Ihr Coiffeur an der Vorstadt 4.</p>${contact('Termin anfragen')}</div><div class="sd-holiday-photo">${salonImage || '<span aria-hidden="true">H</span>'}</div></section>
      <section class="sd-holiday-salon sd-section" id="salon"><span class="sd-kicker">01 / Salon</span><div><h2>Willkommen<br>bei Holiday.</h2><p>Coiffeur Holiday befindet sich in Wangen an der Aare. Die bestehende Website nennt Ursula Böhlen als Inhaberin.</p></div></section>
      <section class="sd-holiday-note sd-section"><span class="sd-kicker">Hinweis</span><h2>Ferien im Herbst.</h2><p>Auf der Original-Website sind Ferien vom 24. September bis 12. Oktober 2026 angekündigt. Bitte berücksichtigen Sie die Pause bei Ihrer Anfrage.</p></section>
      <section class="sd-holiday-visit sd-section" id="besuch"><div><span class="sd-kicker">02 / Besuch</span><h2>Vorstadt 4.</h2><p>3380 Wangen an der Aare</p></div><div class="sd-holiday-fact"><span>Telefon</span><strong>${e(lead.phone)}</strong></div></section>
      <section class="sd-holiday-contact sd-section" id="kontakt"><span class="sd-kicker">03 / Kontakt</span><h2>Fragen oder<br>Terminwunsch?</h2><p class="sd-date-note"><strong>Ferien:</strong> 24. September bis 12. Oktober 2026.</p>${contact('Termin anfragen')}<p>Bitte prüfen Sie aktuelle Öffnungszeiten direkt beim Salon.</p></section>
    </main>${footer(lead, 'Vorstadt 4, 3380 Wangen an der Aare')}</div>`;
  return { html, css };
}

export function render(lead) {
  switch (lead.slug) {
    case 'sopra': return sopra(lead);
    case 'wacker': return wacker(lead);
    case 'coiffeur-lanz': return lanz(lead);
    case 'hairstudio-f': return hairstudio(lead);
    case 'holiday': return holiday(lead);
    default: throw new Error(`Unsupported salon-dining lead: ${lead.slug}`);
  }
}

const css = `
.sd-site{--paper:#f5f2ec;--ink:#24241f;--muted:#635f55;--line:#c8c2b7;--accent:#394a34;--accent-text:#fff;color:var(--ink);background:var(--paper);font-family:Arial,Helvetica,sans-serif;line-height:1.45;overflow:hidden}
.sd-site .sd-date-note{border-left:3px solid var(--accent);padding:.65rem .85rem;margin:1.25rem 0;color:var(--ink);background:color-mix(in srgb,var(--accent) 9%,var(--paper));font-size:.9rem;line-height:1.45;max-width:38ch}.sd-site .sd-date-note strong{font-weight:800}.sd-holiday-contact .sd-date-note{margin:1.5rem auto 0;text-align:left}
.sd-site *{box-sizing:border-box}.sd-site img{display:block;width:100%;height:100%;object-fit:cover}.sd-site a{color:inherit}.sd-site button{font:inherit;cursor:pointer}.sd-site h1,.sd-site h2,.sd-site h3,.sd-site p{margin:0}.sd-site h1,.sd-site h2{line-height:.98;letter-spacing:-.055em}.sd-site h1{font-size:clamp(3.3rem,8.5vw,9rem)}.sd-site h2{font-size:clamp(2.6rem,6vw,6.5rem)}.sd-site p{max-width:52ch}.sd-site section{scroll-margin-top:5rem}.sd-header{min-height:76px;display:flex;align-items:center;justify-content:space-between;gap:2rem;padding:0 clamp(1.25rem,4vw,4.5rem);border-bottom:1px solid var(--line)}.sd-brand{font-weight:800;text-decoration:none;letter-spacing:-.045em;font-size:1.2rem;white-space:nowrap}.sd-nav{display:flex;align-items:center;gap:clamp(1rem,2vw,2rem)}.sd-nav a{text-decoration:none;font-size:.86rem;font-weight:700}.sd-nav a:hover,.sd-text-link:hover,.sd-source:hover{text-decoration:underline;text-underline-offset:5px}.sd-menu{display:none;color:var(--ink);background:none;border:1px solid var(--line);padding:.5rem .8rem}.sd-button{border:0;background:var(--accent);color:var(--accent-text);padding:.9rem 1.25rem;font-weight:700;white-space:nowrap;min-height:44px;transition:transform .18s ease,opacity .18s ease}.sd-button:hover{transform:translateY(-2px);opacity:.9}.sd-button:focus-visible,.sd-site a:focus-visible,.sd-menu:focus-visible{outline:3px solid var(--accent);outline-offset:3px}.sd-kicker{display:block;font-size:.72rem;text-transform:uppercase;letter-spacing:.17em;font-weight:800;margin-bottom:1.5rem}.sd-section{padding:clamp(4.5rem,8vw,8rem) clamp(1.25rem,6vw,7rem);border-top:1px solid var(--line)}.sd-actions{display:flex;align-items:center;gap:1.7rem;flex-wrap:wrap;margin-top:2rem}.sd-text-link{font-weight:700;text-decoration:none;border-bottom:1px solid currentColor;padding:.5rem 0}.sd-hours{border-top:2px solid var(--ink);padding-top:1rem;max-width:32rem}.sd-hours h3{font-size:1.5rem;letter-spacing:-.03em;margin-bottom:1rem}.sd-hours p{display:flex;justify-content:space-between;gap:1rem;border-bottom:1px solid var(--line);padding:.8rem 0;font-size:.9rem}.sd-hours b{text-align:right}.sd-hours small{display:block;margin-top:1.5rem}.sd-footer{padding:2rem clamp(1.25rem,6vw,7rem);border-top:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;gap:1rem;flex-wrap:wrap;font-size:.85rem}.sd-footer strong{font-size:1.05rem}.sd-source{text-underline-offset:4px}
.sd-sopra{--paper:#f4f0e7;--ink:#302e25;--muted:#706b5f;--line:#c7c1b4;--accent:#9d4f2f}.sd-sopra h1,.sd-sopra h2{font-family:Georgia,'Times New Roman',serif;font-weight:400}.sd-sopra-hero{display:grid;grid-template-columns:1.02fr .98fr;min-height:min(760px,85vh)}.sd-sopra-intro{padding:clamp(3rem,8vw,8rem) clamp(1.25rem,6vw,7rem);align-self:center}.sd-sopra-intro p{font-size:1.15rem;margin-top:1.6rem}.sd-sopra-intro em{font-weight:400}.sd-sopra-image{position:relative;background:#a28467;min-height:460px;overflow:hidden}.sd-sopra-image img{position:absolute;inset:0}.sd-sopra-type{position:absolute;inset:0;display:grid;place-items:center;font-family:Georgia,serif;font-size:clamp(4rem,10vw,10rem);color:#fff;letter-spacing:-.08em}.sd-image-caption{position:absolute;bottom:1.4rem;right:1.4rem;color:#fff;font-size:.75rem;text-transform:uppercase;letter-spacing:.16em;text-shadow:0 1px 5px #000}.sd-sopra-food{display:grid;grid-template-columns:1fr 1fr;gap:5rem}.sd-sopra-food .sd-section-body{padding-top:2rem}.sd-sopra-food .sd-section-body>p{font-size:1.2rem;margin-bottom:3rem}.sd-offer-line{display:flex;justify-content:space-between;gap:1rem;border-top:1px solid var(--line);padding:1rem 0}.sd-offer-line span{color:var(--muted)}.sd-sopra-about{display:grid;grid-template-columns:.8fr 1.2fr;gap:clamp(2rem,10vw,10rem);align-items:center}.sd-about-image{height:440px;background:#c8b7a6;display:grid;place-items:center;font:13rem Georgia,serif}.sd-sopra-about p{margin-top:2rem;font-size:1.15rem}.sd-sopra-visit{display:grid;grid-template-columns:1fr 1fr;gap:4rem}.sd-sopra-visit p{margin:2rem 0}.sd-sopra .sd-button{border-radius:0}
.sd-wacker{--paper:#f1f2ec;--ink:#1e3129;--muted:#56635a;--line:#bfc9bf;--accent:#164b3f}.sd-wacker .sd-brand{text-transform:uppercase;letter-spacing:.08em}.sd-wacker h1,.sd-wacker h2{font-weight:800}.sd-wacker-hero{position:relative;min-height:620px;display:grid;grid-template-columns:1.1fr .9fr}.sd-wacker-photo{background:#789180;overflow:hidden;display:grid;place-items:center;font-weight:900;font-size:6rem;color:#fff;letter-spacing:-.07em}.sd-wacker-photo img{max-height:660px}.sd-wacker-title{padding:clamp(3rem,7vw,7rem) clamp(1.25rem,6vw,6rem);align-self:center}.sd-wacker-title h1{font-size:clamp(3.5rem,7vw,7rem)}.sd-wacker-title i{font-weight:400}.sd-wacker-title p{font-size:1.16rem;margin:1.8rem 0}.sd-wacker-menu{display:grid;grid-template-columns:1fr .9fr;gap:5rem}.sd-wacker-menu p{font-size:1.13rem;margin-bottom:2rem}.sd-wacker-list{list-style:none;padding:0;margin:0}.sd-wacker-list li{border-top:1px solid var(--line);padding:1rem 0;font-size:1.4rem;font-weight:700;display:flex;gap:2rem}.sd-wacker-list span{font-size:.7rem;letter-spacing:.1em;padding-top:.5rem}.sd-wacker-lunch{display:grid;grid-template-columns:1fr 1fr;gap:4rem;align-items:center}.sd-lunch-copy p{margin:2rem 0;font-size:1.13rem}.sd-lunch-image{height:450px;background:#a6b8a8;display:grid;place-items:center;font-size:12rem;font-weight:800}.sd-wacker-charbonnade{text-align:center}.sd-wacker-charbonnade p{margin:2rem auto 0}.sd-wacker-visit{display:grid;grid-template-columns:1fr 1fr;gap:4rem}.sd-wacker-visit p{margin:2rem 0}.sd-wacker .sd-button{border-radius:2px}
.sd-lanz{--paper:#f6f5ef;--ink:#182824;--muted:#60706a;--line:#bac6bf;--accent:#285849}.sd-lanz .sd-brand{font-weight:500;letter-spacing:-.03em}.sd-lanz .sd-button{border-radius:999px}.sd-lanz-hero{min-height:610px;padding:clamp(4rem,7vw,7rem) clamp(1.25rem,7vw,8rem) 3rem;display:flex;flex-direction:column;justify-content:space-between}.sd-lanz-hero h1{font-size:clamp(5.1rem,14vw,15rem);font-weight:500;line-height:.8}.sd-lanz-hero h1 span{color:var(--accent);padding-left:17vw}.sd-lanz-hero-bottom{display:flex;justify-content:space-between;align-items:end;gap:2rem}.sd-lanz-line{display:grid;grid-template-columns:.45fr 1.1fr .8fr;gap:2rem;align-items:start}.sd-lanz-line p{font-size:1.1rem;padding-top:1rem}.sd-lanz-location{background:#dce8df;display:grid;grid-template-columns:.45fr 1fr .4fr;gap:2rem;align-items:start}.sd-lanz-location address{font-style:normal;font-size:1.4rem;margin-top:2rem}.sd-lanz-stamp{border:1px solid currentColor;border-radius:50%;width:7rem;height:7rem;display:grid;place-items:center;text-align:center;line-height:1.1;transform:rotate(-15deg);font-weight:800;letter-spacing:.1em}.sd-lanz-contact{display:grid;grid-template-columns:.45fr 1fr .8fr;gap:2rem}.sd-lanz-contact p{font-size:1.05rem;line-height:1.8}.sd-lanz-contact .sd-button{grid-column:2;justify-self:start}
.sd-hairstudio{--paper:#f4f1f0;--ink:#29212a;--muted:#6c5f6b;--line:#cec0cb;--accent:#7e3c60}.sd-hairstudio .sd-brand{font-style:italic}.sd-hairstudio .sd-button{border-radius:2rem}.sd-hairstudio-hero{display:grid;grid-template-columns:1fr .68fr;min-height:620px}.sd-hairstudio-hero>div:first-child{padding:clamp(3rem,7vw,7rem) clamp(1.25rem,6vw,7rem)}.sd-hairstudio-hero h1{font-size:clamp(4.6rem,10vw,10rem);line-height:.85}.sd-hairstudio-hero h1 em{color:var(--accent)}.sd-hairstudio-hero p{font-size:1.1rem;margin:2rem 0}.sd-hairstudio-hero-side{background:#e0ccd9;display:flex;flex-direction:column;justify-content:space-between;padding:2rem;overflow:hidden}.sd-hairstudio-hero-side span{font-size:clamp(15rem,43vw,43rem);line-height:.75;letter-spacing:-.15em;font-weight:900;color:#a86e92;transform:rotate(-8deg)}.sd-hairstudio-hero-side p{align-self:end;text-transform:uppercase;font-size:.8rem;letter-spacing:.15em;font-weight:800}.sd-hairstudio-services{display:grid;grid-template-columns:.5fr .7fr 1fr;gap:2rem}.sd-service-list>div{display:flex;gap:2rem;border-top:1px solid var(--line);padding:1rem 0}.sd-service-list span{font-size:.75rem}.sd-service-list strong{font-size:1.12rem}.sd-hairstudio-about{background:#e9dfe5;display:grid;grid-template-columns:.5fr 1.2fr 1fr;gap:2rem}.sd-hairstudio-about p{font-size:1.1rem;align-self:end}.sd-hairstudio-visit{display:grid;grid-template-columns:1fr 1fr;gap:4rem}.sd-hairstudio-visit p{margin:2rem 0}
.sd-holiday{--paper:#f2f4f2;--ink:#192e32;--muted:#5d6d70;--line:#bfd0d0;--accent:#25616b}.sd-holiday .sd-brand{letter-spacing:.08em;text-transform:uppercase}.sd-holiday .sd-button{border-radius:0}.sd-holiday-hero{display:grid;grid-template-columns:1.05fr .95fr;min-height:610px}.sd-holiday-title{padding:clamp(3rem,7vw,7rem) clamp(1.25rem,6vw,7rem);align-self:center}.sd-holiday-title h1{font-weight:500}.sd-holiday-title h1 i{font-weight:300;color:var(--accent)}.sd-holiday-title p{font-size:1.2rem;margin:2rem 0}.sd-holiday-photo{background:#c2d6d5;display:grid;place-items:center;overflow:hidden;font-size:20rem;color:#79a6a9;font-weight:700}.sd-holiday-salon{display:grid;grid-template-columns:.4fr 1.2fr;gap:3rem}.sd-holiday-salon p{font-size:1.15rem;margin-top:2rem}.sd-holiday-note{display:grid;grid-template-columns:.4fr 1fr 1fr;gap:3rem;background:#e1ebea;align-items:start}.sd-holiday-note h2{font-size:clamp(2.4rem,5vw,5rem)}.sd-holiday-note p{font-size:1.05rem}.sd-holiday-visit{display:grid;grid-template-columns:1fr .6fr;gap:3rem}.sd-holiday-visit p{font-size:1.3rem;margin-top:1.5rem}.sd-holiday-fact{border-top:2px solid var(--ink);padding-top:1rem;display:flex;justify-content:space-between;gap:1rem}.sd-holiday-contact{text-align:center}.sd-holiday-contact .sd-button{margin:2rem 0}.sd-holiday-contact p{margin:0 auto;color:var(--muted)}
@media(max-width:900px){.sd-header{position:relative;min-height:68px}.sd-menu{display:block}.sd-nav{display:none;position:absolute;top:100%;left:0;right:0;z-index:20;background:var(--paper);border-bottom:1px solid var(--line);padding:1rem 1.25rem 1.4rem;flex-direction:column;align-items:stretch}.sd-nav.open{display:flex}.sd-nav a{padding:.6rem 0}.sd-nav .sd-button{align-self:start}.sd-sopra-hero,.sd-wacker-hero,.sd-hairstudio-hero,.sd-holiday-hero{grid-template-columns:1fr}.sd-sopra-hero,.sd-wacker-hero,.sd-hairstudio-hero,.sd-holiday-hero{min-height:0}.sd-sopra-intro,.sd-wacker-title,.sd-hairstudio-hero>div:first-child,.sd-holiday-title{padding:3.5rem 1.25rem}.sd-sopra-image,.sd-wacker-photo,.sd-holiday-photo{min-height:330px;max-height:430px}.sd-wacker-photo{order:2}.sd-wacker-title{order:1}.sd-hairstudio-hero-side{display:none}.sd-sopra-food,.sd-sopra-about,.sd-sopra-visit,.sd-wacker-menu,.sd-wacker-lunch,.sd-wacker-visit,.sd-hairstudio-visit,.sd-holiday-visit{grid-template-columns:1fr;gap:2.5rem}.sd-sopra-about .sd-about-image{height:360px}.sd-lanz-line,.sd-lanz-location,.sd-lanz-contact,.sd-hairstudio-services,.sd-hairstudio-about,.sd-holiday-salon,.sd-holiday-note{grid-template-columns:1fr;gap:1.5rem}.sd-lanz-contact .sd-button{grid-column:auto}.sd-lanz-hero{min-height:550px}.sd-lanz-hero h1 span{padding-left:10vw}}
@media(max-width:520px){.sd-site h1{font-size:clamp(3.3rem,16vw,5.6rem)}.sd-site h2{font-size:clamp(2.5rem,12vw,4rem)}.sd-section{padding:4.5rem 1.25rem}.sd-brand{white-space:normal;font-size:1rem}.sd-sopra-intro,.sd-wacker-title,.sd-hairstudio-hero>div:first-child,.sd-holiday-title{padding:3.5rem 1.25rem}.sd-wacker-title h1,.sd-lanz-hero h1,.sd-hairstudio-hero h1{font-size:clamp(3.3rem,15vw,5.7rem)}.sd-sopra-image,.sd-wacker-photo,.sd-holiday-photo{min-height:260px;height:300px}.sd-wacker-photo img{height:100%}.sd-lanz-hero{min-height:480px;padding:4rem 1.25rem 2rem}.sd-lanz-hero h1{line-height:.93}.sd-lanz-hero h1 span{padding-left:4rem}.sd-lanz-hero-bottom{align-items:start;flex-direction:column}.sd-lanz-stamp{width:5rem;height:5rem}.sd-about-image,.sd-lunch-image{height:280px}.sd-hours p{display:block}.sd-hours b{display:block;text-align:left}.sd-footer{align-items:start;flex-direction:column}}
@media(prefers-color-scheme:dark){.sd-sopra{--paper:#24231f;--ink:#f4eee3;--muted:#d1c5b4;--line:#595449;--accent:#c47958;--accent-text:#221b17}.sd-wacker{--paper:#17251f;--ink:#e8eee7;--muted:#b9c9bc;--line:#4f6557;--accent:#9bd0ac;--accent-text:#17251f}.sd-lanz{--paper:#162820;--ink:#edf4eb;--muted:#bccfc0;--line:#506659;--accent:#a5d6b5;--accent-text:#172820}.sd-hairstudio{--paper:#291f29;--ink:#f4ebf2;--muted:#d4c3d0;--line:#665363;--accent:#d994ba;--accent-text:#291f29}.sd-holiday{--paper:#15282b;--ink:#edf4f2;--muted:#c3d4d4;--line:#506b6b;--accent:#9bd2d3;--accent-text:#15282b}.sd-lanz-location,.sd-hairstudio-about,.sd-holiday-note{background:#2c4137}.sd-hairstudio-about{background:#423440}.sd-holiday-note{background:#284244}.sd-hairstudio-hero-side{background:#483746}.sd-hairstudio-hero-side span{color:#805976}}
@media(prefers-reduced-motion:reduce){.sd-site *, .sd-site *::before,.sd-site *::after{scroll-behavior:auto!important;transition:none!important;animation:none!important}}
`;
