import { escapeHtml as e } from '../lib.mjs';

const asset = (lead, hint, index = 0) => {
  const assets = (lead.assets || []).filter(item => /\.(jpe?g|png|webp)$/i.test(item.path || ''));
  return assets.find(item => `${item.url || ''} ${item.path || ''}`.toLowerCase().includes(hint.toLowerCase())) || assets[index];
};

const photo = (item, className, alt) => item
  ? `<img class="${className}" src="../../${e(item.path)}" alt="${e(item.alt || alt)}" width="${Number(item.width) || 1200}" height="${Number(item.height) || 800}" loading="lazy">`
  : `<div class="${className} wood-image-placeholder" aria-hidden="true"></div>`;

const contact = (lead, place = lead.locality) => `<section class="wood-contact" id="kontakt"><div><p class="wood-kicker">Kontakt</p><h2>Ein Vorhaben aus Holz?</h2><p>Wir freuen uns auf Ihre Anfrage.</p></div><div class="wood-contact-details"><strong>${e(lead.name)}</strong><span>${e(place)}</span><span>${e(lead.phone || '')}</span><button class="wood-button" type="button" data-demo-contact>Kontakt aufnehmen <span aria-hidden="true">↗</span></button></div></section>`;

const shell = (lead, variant, navLinks, body, place) => `<div class="wood wood-${variant}"><header class="wood-header"><a class="wood-brand" href="#start" aria-label="${e(lead.name)} zur Startseite">${e(lead.name)}</a><button class="wood-menu" type="button" data-menu-toggle aria-controls="site-nav" aria-expanded="false">Menü <span aria-hidden="true">☰</span></button><nav id="site-nav" aria-label="Hauptnavigation">${navLinks.map(([label, id]) => `<a href="#${id}">${e(label)}</a>`).join('')}<button type="button" data-demo-contact>Kontakt <span aria-hidden="true">↗</span></button></nav></header><main id="start">${body}${contact(lead, place)}</main><footer class="wood-footer"><span>${e(lead.name)} · ${e(place || lead.locality)}</span><a href="${e(lead.website)}" target="_blank" rel="noopener noreferrer">Original-Website als Quelle ↗</a></footer></div>`;

function bernhof(lead) {
  const hero = asset(lead, 'i0363ad', 1);
  const detail = asset(lead, 'ia9e3c', 2);
  const body = `<section class="wood-hero bern-hero"><div class="bern-intro"><p class="wood-kicker">Holzhandwerk aus Frümsen</p><h1>Türen, die Räume prägen.</h1><p>Haustüren, Innentüren und Innenausbau von BERNHOF-Vetsch AG.</p><div class="wood-actions"><a class="wood-button" href="#leistungen">Leistungen entdecken <span aria-hidden="true">↘</span></a><button class="wood-text-button" type="button" data-demo-contact>Projekt besprechen ↗</button></div></div><div class="bern-hero-image">${photo(hero, 'wood-photo', 'Einblick in die Arbeiten von BERNHOF-Vetsch')}</div><span class="bern-side-label">BERNHOF / VETSCH</span></section>
  <section class="bern-services wood-section" id="leistungen"><div class="wood-section-heading"><p class="wood-kicker">Leistungen</p><h2>Vom Eingang bis ins Innere.</h2></div><div class="bern-service-list"><article><span>01</span><h3>Haustüren</h3><p>Der erste Eindruck eines Hauses.</p></article><article><span>02</span><h3>Innentüren</h3><p>Übergänge zwischen den Räumen.</p></article><article><span>03</span><h3>Innenausbau</h3><p>Schreinerei für den Wohnraum.</p></article><article><span>04</span><h3>Schränke & Garderoben</h3><p>Stauraum am richtigen Ort.</p></article></div></section>
  <section class="bern-feature wood-section" id="handwerk"><div class="bern-feature-image">${photo(detail, 'wood-photo', 'Detail aus dem Holzhandwerk')}</div><div><p class="wood-kicker">Weitere Arbeiten</p><h2>Auch für besondere Anforderungen.</h2><p>Zum Angebot gehören Brandschutz-VKF-Türen EI 30, Wohnungs-Servicearbeiten und Glasbruch-Reparaturen.</p><button class="wood-text-button" type="button" data-demo-contact>Frage stellen ↗</button></div></section>`;
  return shell(lead, 'bernhof', [['Leistungen','leistungen'],['Handwerk','handwerk'],['Kontakt','kontakt']], body, 'im Hof 3 · 9467 Frümsen');
}

function fuhrer(lead) {
  const body = `<section class="wood-hero fuhrer-hero"><div class="fuhrer-rule"><span>F / S</span><span>Kehrsatz · Bern</span></div><div class="fuhrer-hero-grid"><div><p class="wood-kicker">Fuhrer Schreinerei AG</p><h1>Fenster. Türen. Räume.</h1></div><div class="fuhrer-hero-aside"><p>Die Fenster und Türenfabrik in Kehrsatz, mit Arbeiten im Innenausbau.</p><a class="wood-button" href="#arbeiten">Arbeiten ansehen <span aria-hidden="true">↘</span></a></div></div><div class="fuhrer-bars" aria-hidden="true"><span></span><span></span><span></span></div></section>
  <section class="fuhrer-scope wood-section" id="arbeiten"><p class="wood-kicker">Arbeitsbereiche</p><div class="fuhrer-scope-grid"><article><span>01 / Öffnungen</span><h2>Fenster & Türen</h2><p>Zwei Kernbereiche, klar im Mittelpunkt.</p></article><article><span>02 / Innen</span><h2>Innenausbau</h2><p>Schreinerarbeiten für Räume und Ausbau.</p></article><article><span>03 / Bau</span><h2>Spezialmontagen</h2><p>Ergänzt durch kleinere Zimmerarbeiten.</p></article></div></section>
  <section class="fuhrer-detail wood-section" id="erweitert"><div class="fuhrer-detail-title"><p class="wood-kicker">Erweitertes Angebot</p><h2>Arbeiten am Gebäude.</h2></div><div class="fuhrer-detail-lines"><p>Dachausbauten und Lukarnen inklusive Fenster</p><p>Dachflächenfenster und Fassadensanierungen</p><p>Dachreparaturen und Carports</p></div></section>`;
  return shell(lead, 'fuhrer', [['Arbeiten','arbeiten'],['Angebot','erweitert'],['Kontakt','kontakt']], body, 'Kirchackerweg 31 · 3122 Kehrsatz');
}

function bieri(lead) {
  const main = asset(lead, 'ib7d59', 1);
  const second = asset(lead, 'i577f', 2);
  const body = `<section class="wood-hero bieri-hero"><div class="bieri-copy"><p class="wood-kicker">Fredy Bieri AG · Schötz</p><h1>Raum für das Leben darin.</h1><p>Küchen, Möbel und Innenausbau aus der Schreinerei.</p><a class="wood-button" href="#raeume">Räume entdecken <span aria-hidden="true">↘</span></a></div><div class="bieri-picture">${photo(main, 'wood-photo', 'Schreinerei-Arbeit der Fredy Bieri AG')}<span>Schötz / Triengen</span></div></section>
  <section class="bieri-rooms wood-section" id="raeume"><div class="wood-section-heading"><p class="wood-kicker">Für Zuhause und mehr</p><h2>Jeder Raum hat seine Aufgabe.</h2></div><div class="bieri-room-grid"><article class="bieri-main-room"><span>01</span><h3>Küchen</h3><p>Bieri Küchen als eigener Schwerpunkt.</p></article><article><span>02</span><h3>Schränke & Möbel</h3><p>Stauraum und Einrichtung.</p></article><article><span>03</span><h3>Badezimmer</h3><p>Schreinerarbeiten im Bad.</p></article></div></section>
  <section class="bieri-material wood-section" id="material"><div>${photo(second, 'wood-photo', 'Weitere Arbeit der Fredy Bieri AG')}</div><div><p class="wood-kicker">Böden & Ausbau</p><h2>Eine Grundlage, viele Möglichkeiten.</h2><p>Parkett, Laminat und Vinyl gehören ebenso zum Angebot wie Umbauten sowie Gastro- und Ladenbau.</p><button class="wood-text-button" type="button" data-demo-contact>Vorhaben besprechen ↗</button></div></section>`;
  return shell(lead, 'bieri', [['Räume','raeume'],['Material','material'],['Kontakt','kontakt']], body, 'Nebikerstrasse 40 · 6247 Schötz');
}

function schreinerzwei(lead) {
  const main = asset(lead, 'header_tueren', 1);
  const detail = asset(lead, 'header_moebel', 2);
  const body = `<section class="wood-hero zwei-hero"><div class="zwei-symbol" aria-hidden="true">2</div><div class="zwei-title"><p class="wood-kicker">Schreiner2 AG / Gampelen</p><h1>Ideen nehmen Form an.</h1><p>Schreinerei für Möbel, Fenster, Türen und Innenausbau.</p><a class="wood-button" href="#felder">Arbeiten entdecken <span aria-hidden="true">↘</span></a></div><div class="zwei-hero-image">${photo(main, 'wood-photo', 'Arbeit der Schreiner2 AG')}</div></section>
  <section class="zwei-fields wood-section" id="felder"><div class="wood-section-heading"><p class="wood-kicker">Was wir machen</p><h2>Fünf Felder. Ein Materialgefühl.</h2></div><div class="zwei-field-grid"><span>Möbel</span><span>Fenster</span><span>Türen</span><span>Parkett</span><span>Innenausbau</span></div></section>
  <section class="zwei-studio wood-section" id="schreinerei"><div class="zwei-studio-copy"><p class="wood-kicker">Schreinerei</p><h2>Vom einzelnen Möbel bis zum ganzen Raum.</h2><p>Die Arbeiten verbinden Einrichtung und Ausbau. Welche Lösung passt, beginnt mit einem Gespräch.</p><button class="wood-text-button" type="button" data-demo-contact>Kontakt aufnehmen ↗</button></div><div>${photo(detail, 'wood-photo', 'Weiteres Schreiner2-Motiv')}</div></section>`;
  return shell(lead, 'zwei', [['Arbeiten','felder'],['Schreinerei','schreinerei'],['Kontakt','kontakt']], body, 'Gewerbestrasse 10 · 3236 Gampelen');
}

function fritschi(lead) {
  const holz = asset(lead, 'FriGri_Bereich_Holzbau', 0);
  const schreinerei = asset(lead, 'FriGri_Bereich_Schreinerei', 1);
  const dach = asset(lead, 'FriGri_Bereich_Bedachungen', 2);
  const body = `<section class="wood-hero fg-hero"><div class="fg-hero-copy"><p class="wood-kicker">Güttingen · Kreuzlingen</p><h1>Holzbau. Schreinerei. Mehr.</h1><p>Fritschi + Griesemer AG verbindet Holzbau, Schreinerei, Dach und Gebäudehülle.</p><a class="wood-button" href="#bereiche">Bereiche ansehen <span aria-hidden="true">↘</span></a></div><div class="fg-hero-image"><div>${photo(holz, 'wood-photo', 'Holzbau der Fritschi + Griesemer AG')}</div><div>${photo(dach, 'wood-photo', 'Bedachungen der Fritschi + Griesemer AG')}</div></div></section>
  <section class="fg-intro wood-section" id="bereiche"><p class="wood-kicker">Bereiche</p><h2>Ein Gebäude. Viele Aufgaben.</h2><div class="fg-department-list"><span>Holzbau</span><span>Schreinerei</span><span>Bedachungen</span><span>Spenglerei</span><span>Dämmung</span><span>Service & Unterhalt</span></div></section>
  <section class="fg-feature wood-section" id="planung"><div>${photo(schreinerei, 'wood-photo', 'Schreinerei der Fritschi + Griesemer AG')}</div><div><p class="wood-kicker">Von der Planung bis zum Unterhalt</p><h2>Arbeiten am Bau, im Raum und am Dach.</h2><p>Beratung und Planung, Elementbau und Unterhaltsarbeiten gehören zum belegten Angebot.</p><button class="wood-text-button" type="button" data-demo-contact>Projekt anfragen ↗</button></div></section>`;
  return shell(lead, 'fg', [['Bereiche','bereiche'],['Planung','planung'],['Kontakt','kontakt']], body, 'Güttingen · Kreuzlingen');
}

const css = `
.wood{--paper:#f3f0e8;--ink:#243027;--muted:#5f6d61;--accent:#af5b36;--line:rgba(36,48,39,.22);--surface:#e8e2d5;background:var(--paper);color:var(--ink);font-family:Arial,Helvetica,sans-serif;overflow:hidden}
.wood *{box-sizing:border-box}.wood a{color:inherit}.wood button{font:inherit;cursor:pointer}.wood img{display:block;max-width:100%;height:auto}.wood-photo{width:100%;height:100%!important;object-fit:cover}.wood-image-placeholder{background:linear-gradient(140deg,var(--surface),var(--paper));min-height:16rem}
.wood-header{min-height:78px;display:flex;align-items:center;justify-content:space-between;gap:1.5rem;padding:1rem clamp(1.25rem,4vw,4rem);border-bottom:1px solid var(--line)}.wood-brand{font-size:clamp(1rem,1.6vw,1.3rem);font-weight:800;letter-spacing:-.04em;text-decoration:none;max-width:15rem;line-height:1.05}.wood-header nav{display:flex;align-items:center;gap:clamp(1rem,2vw,2rem)}.wood-header nav a{text-decoration:none;font-size:.88rem}.wood-header nav button{border:1px solid currentColor;background:none;color:inherit;padding:.65rem .9rem}.wood-menu{display:none;border:0;background:none;color:inherit;font-weight:700}.wood-section{padding:clamp(4.5rem,8vw,9rem) clamp(1.25rem,5vw,6rem)}.wood-kicker{font-size:.72rem!important;text-transform:uppercase;letter-spacing:.16em;font-weight:800;margin:0 0 1.5rem!important;color:var(--accent)}.wood h1,.wood h2,.wood h3,.wood p{margin-top:0}.wood h1{font-size:clamp(3.3rem,6.5vw,7.2rem);line-height:.99;letter-spacing:-.065em;margin-bottom:1.4rem;max-width:12ch}.wood h2{font-size:clamp(2.4rem,4.6vw,5.1rem);line-height:1.04;letter-spacing:-.055em;margin-bottom:1.4rem;max-width:14ch}.wood h3{font-size:clamp(1.5rem,2.2vw,2.3rem);line-height:1.1;letter-spacing:-.04em}.wood p{font-size:clamp(1rem,1.3vw,1.18rem);line-height:1.55;max-width:54ch}.wood-button{display:inline-flex;align-items:center;justify-content:space-between;gap:1.6rem;background:var(--accent);border:1px solid var(--accent);color:white!important;padding:.95rem 1.2rem;text-decoration:none;font-weight:700;font-size:.91rem;white-space:nowrap;transition:transform .2s ease,background .2s ease}.wood-button:hover{transform:translateY(-3px)}.wood-text-button{border:0;border-bottom:1px solid currentColor;background:none;color:var(--ink);padding:.6rem 0;font-weight:700}.wood-text-button:hover{color:var(--accent)}.wood-actions{display:flex;align-items:center;flex-wrap:wrap;gap:1.5rem}.wood-contact{background:var(--ink);color:var(--paper);padding:clamp(4rem,7vw,7rem) clamp(1.25rem,5vw,6rem);display:grid;grid-template-columns:1.5fr 1fr;gap:3rem}.wood-contact .wood-kicker{color:var(--paper);opacity:.7}.wood-contact h2{max-width:12ch}.wood-contact-details{display:flex;flex-direction:column;align-items:flex-start;justify-content:center;gap:.8rem}.wood-contact-details strong{font-size:1.25rem}.wood-contact-details .wood-button{margin-top:1rem}.wood-footer{display:flex;justify-content:space-between;gap:1rem;align-items:center;padding:1.4rem clamp(1.25rem,5vw,6rem);font-size:.82rem}.wood-footer a{text-underline-offset:3px}.wood a:focus-visible,.wood button:focus-visible{outline:3px solid var(--accent);outline-offset:4px}
.wood-bernhof{--paper:#eee9df;--ink:#302b24;--muted:#736b60;--accent:#a04427;--surface:#d8cabc}.bern-hero{min-height:690px;display:grid;grid-template-columns:minmax(0,1.02fr) minmax(0,.98fr);position:relative}.bern-intro{padding:clamp(4rem,7vw,7rem) clamp(1.25rem,5vw,6rem);align-self:center}.bern-intro h1{max-width:10ch}.bern-hero-image{min-height:590px;overflow:hidden}.bern-side-label{position:absolute;right:0;bottom:0;background:var(--accent);color:white;padding:.7rem 1rem;font-size:.7rem;letter-spacing:.2em}.bern-services{display:grid;grid-template-columns:.9fr 1.1fr;gap:5vw}.bern-service-list article{display:grid;grid-template-columns:3rem 1fr;column-gap:1rem;border-top:1px solid var(--line);padding:1.2rem 0}.bern-service-list article span{font-size:.75rem;color:var(--accent);padding-top:.35rem}.bern-service-list h3{margin:0}.bern-service-list p{grid-column:2;margin:.5rem 0 0;color:var(--muted)}.bern-feature{background:var(--surface);display:grid;grid-template-columns:1fr .8fr;align-items:center;gap:clamp(2rem,8vw,9rem)}.bern-feature-image{height:480px}.bern-feature .wood-text-button{margin-top:1rem}
.wood-fuhrer{--paper:#edf0ee;--ink:#173832;--muted:#517069;--accent:#bd5235;--surface:#dce4df}.fuhrer-hero{padding:2rem clamp(1.25rem,5vw,6rem) 0;min-height:650px;display:flex;flex-direction:column;justify-content:space-between}.fuhrer-rule{display:flex;justify-content:space-between;border-bottom:2px solid var(--ink);padding-bottom:1rem;font-size:.82rem;font-weight:800}.fuhrer-hero-grid{display:grid;grid-template-columns:1.5fr .6fr;gap:4rem;align-items:end;padding:3rem 0 5rem}.fuhrer-hero h1{font-size:clamp(4.3rem,9vw,10rem);max-width:9ch;text-transform:uppercase;line-height:.86}.fuhrer-hero-aside{padding-bottom:1rem}.fuhrer-bars{display:grid;grid-template-columns:1fr 1fr 1fr;gap:.5rem;height:35px}.fuhrer-bars span{background:var(--accent)}.fuhrer-bars span:nth-child(2){background:var(--ink)}.fuhrer-bars span:nth-child(3){background:var(--surface)}.fuhrer-scope-grid{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid var(--line);margin-top:3rem}.fuhrer-scope article{padding:2rem 2rem 0 0;border-right:1px solid var(--line)}.fuhrer-scope article+article{padding-left:2rem}.fuhrer-scope article:last-child{border:0}.fuhrer-scope article span{font-size:.76rem;color:var(--accent);font-weight:800}.fuhrer-scope h2{font-size:clamp(2rem,3vw,3rem);margin:3rem 0 1rem}.fuhrer-detail{background:var(--surface);display:grid;grid-template-columns:1fr 1fr;gap:4rem}.fuhrer-detail-lines p{border-top:1px solid var(--line);padding:1rem 0;margin:0;font-size:1.2rem}
.wood-bieri{--paper:#f4f0e8;--ink:#3a302a;--muted:#73685e;--accent:#92523a;--surface:#e8ded1}.bieri-hero{display:grid;grid-template-columns:.85fr 1.15fr;min-height:680px}.bieri-copy{padding:clamp(4rem,7vw,8rem) clamp(1.25rem,5vw,6rem);align-self:center}.bieri-copy h1{max-width:10ch}.bieri-picture{position:relative;min-height:600px}.bieri-picture span{position:absolute;bottom:1.5rem;left:1.5rem;background:var(--paper);padding:.65rem 1rem;font-size:.72rem;text-transform:uppercase;letter-spacing:.14em}.bieri-rooms{background:var(--surface)}.bieri-room-grid{display:grid;grid-template-columns:1.2fr 1fr;gap:1rem;margin-top:3rem}.bieri-room-grid article{min-height:235px;padding:2rem;border:1px solid var(--line);display:flex;flex-direction:column;align-items:flex-start;justify-content:flex-end}.bieri-room-grid .bieri-main-room{grid-row:span 2;min-height:486px;background:var(--ink);color:var(--paper)}.bieri-room-grid span{font-size:.75rem;color:var(--accent);margin-bottom:auto}.bieri-room-grid .bieri-main-room span{color:#eabda4}.bieri-room-grid h3{margin:0 0 .5rem}.bieri-room-grid p{margin:0}.bieri-material{display:grid;grid-template-columns:1fr 1fr;gap:7vw;align-items:center}.bieri-material>div:first-child{height:480px}
.wood-zwei{--paper:#f5f6f1;--ink:#202825;--muted:#656d68;--accent:#d55c3e;--surface:#e7eae3}.wood-zwei .wood-brand{text-transform:uppercase;letter-spacing:-.06em}.zwei-hero{min-height:650px;display:grid;grid-template-columns:1.05fr .95fr;position:relative;padding:0 clamp(1.25rem,5vw,6rem)}.zwei-symbol{position:absolute;top:-5rem;left:2vw;font-size:clamp(18rem,42vw,45rem);font-weight:900;line-height:1;color:var(--surface);pointer-events:none}.zwei-title{position:relative;z-index:1;align-self:center;padding:5rem 1rem 5rem 0}.zwei-title h1{max-width:9ch}.zwei-hero-image{height:470px;align-self:end;position:relative;z-index:1}.zwei-fields{background:var(--ink);color:var(--paper)}.zwei-fields .wood-kicker{color:#f1a58f}.zwei-field-grid{display:grid;grid-template-columns:repeat(5,1fr);margin-top:3rem}.zwei-field-grid span{border-top:1px solid rgba(255,255,255,.4);padding:1.2rem .4rem 4rem 0;font-size:clamp(1rem,2vw,1.7rem);font-weight:700}.zwei-studio{display:grid;grid-template-columns:1fr 1fr;gap:6vw;align-items:center}.zwei-studio>div:last-child{height:450px}
.wood-fg{--paper:#f1f2ed;--ink:#1f3430;--muted:#67756e;--accent:#a54133;--surface:#dde5de}.fg-hero{display:grid;grid-template-columns:.9fr 1.1fr;min-height:680px}.fg-hero-copy{padding:clamp(4rem,7vw,8rem) clamp(1.25rem,5vw,6rem);align-self:center}.fg-hero-copy h1{font-size:clamp(3.5rem,5.6vw,6.5rem);max-width:11ch}.fg-hero-image{min-height:600px;display:grid;grid-template-columns:1fr 1fr;gap:.6rem;padding:.6rem;background:var(--ink)}.fg-hero-image>div{min-width:0;overflow:hidden}.fg-intro{background:var(--surface)}.fg-department-list{display:grid;grid-template-columns:repeat(2,1fr);gap:0 4rem;margin-top:3rem}.fg-department-list span{font-size:clamp(1.35rem,2.4vw,2.5rem);font-weight:700;letter-spacing:-.04em;border-top:1px solid var(--line);padding:1.1rem 0}.fg-feature{display:grid;grid-template-columns:1fr .9fr;gap:7vw;align-items:center}.fg-feature>div:first-child{height:490px}
@media(max-width:800px){.wood-header{min-height:68px;position:relative}.wood-menu{display:block}.wood-header nav{display:none;position:absolute;top:100%;left:0;right:0;z-index:10;background:var(--paper);padding:1.3rem;box-shadow:0 12px 24px rgba(0,0,0,.14);flex-direction:column;align-items:stretch}.wood-header nav.open{display:flex}.wood-header nav a,.wood-header nav button{font-size:1rem;padding:.8rem 0}.wood-header nav button{padding:.8rem}.wood-contact{grid-template-columns:1fr}.bern-hero,.bieri-hero,.fg-hero,.zwei-hero{grid-template-columns:1fr}.bern-hero-image,.bieri-picture,.fg-hero-image{min-height:0;height:340px}.zwei-hero-image{height:320px;align-self:auto}.zwei-symbol{top:-1rem;left:1rem}.bern-services,.bern-feature,.bieri-material,.zwei-studio,.fg-feature,.fuhrer-detail{grid-template-columns:1fr}.bern-feature-image,.bieri-material>div:first-child,.zwei-studio>div:last-child,.fg-feature>div:first-child{height:340px}.fuhrer-hero{min-height:570px}.fuhrer-hero-grid{grid-template-columns:1fr;gap:0;padding:3rem 0}.fuhrer-hero h1{font-size:clamp(3.5rem,10vw,6rem)}.fuhrer-hero-aside{max-width:25rem}.fuhrer-scope-grid{grid-template-columns:1fr}.fuhrer-scope article,.fuhrer-scope article+article{padding:1.5rem 0;border-right:0;border-bottom:1px solid var(--line)}.fuhrer-scope h2{margin:1rem 0}.zwei-field-grid{grid-template-columns:repeat(2,1fr)}.zwei-field-grid span{padding-bottom:2rem}.fg-department-list{gap:0 1rem}}
@media(max-width:480px){.wood h1{font-size:clamp(3rem,12vw,4.2rem)}.wood h2{font-size:clamp(2.3rem,9vw,3.2rem)}.wood-footer{flex-direction:column;align-items:flex-start}.wood-actions{align-items:flex-start;flex-direction:column}.bern-intro,.bieri-copy,.fg-hero-copy{padding:4rem 1.25rem}.bern-hero-image,.bieri-picture,.fg-hero-image{height:280px}.zwei-title{padding:4rem 0}.zwei-hero{padding-bottom:1.25rem}.fuhrer-hero{min-height:0}.fuhrer-hero h1{font-size:clamp(3.7rem,14vw,5rem);overflow-wrap:anywhere}.bieri-room-grid{grid-template-columns:1fr}.bieri-room-grid .bieri-main-room{grid-row:auto;min-height:310px}.fg-department-list{grid-template-columns:1fr}.wood-contact h2{max-width:13ch}}
@media(prefers-color-scheme:dark){.wood-bernhof{--paper:#282a26;--ink:#f2eee5;--muted:#b3b6ad;--accent:#b95e40;--surface:#343a34;--line:rgba(255,255,255,.22)}.wood-fuhrer{--paper:#172622;--ink:#f1f4ec;--muted:#a7b9b0;--accent:#bd5235;--surface:#243a34;--line:rgba(255,255,255,.22)}.wood-bieri{--paper:#282421;--ink:#f6eee5;--muted:#bcb0a5;--accent:#ad6246;--surface:#39322c;--line:rgba(255,255,255,.22)}.wood-zwei{--paper:#1e2522;--ink:#f6f7f0;--muted:#b1bbb5;--accent:#d55c3e;--surface:#303a34;--line:rgba(255,255,255,.22)}.wood-fg{--paper:#1d2a26;--ink:#f1f4ec;--muted:#b3c0b5;--accent:#e58d76;--surface:#2a3b34;--line:rgba(255,255,255,.22)}.wood-contact{background:#111a17;color:#f1f3ed}.bieri-room-grid .bieri-main-room,.zwei-fields{background:#111a17;color:#f1f3ed}.wood-button{color:white!important}.wood-fg .wood-button{color:#17221e!important}}
.wood-bernhof{--accent:#873820;--muted:#6c6258}.wood-fuhrer{--accent:#a4412a}.wood-zwei{--accent:#a93d2a}.wood-contact .wood-kicker{color:#f1f3ed;opacity:1}
@media(prefers-color-scheme:dark){.wood-bernhof{--accent:#e7a88a;--muted:#b3b6ad}.wood-fuhrer{--accent:#e6a184}.wood-bieri{--accent:#dca589}.wood-zwei{--accent:#eaa184}.wood-bernhof .wood-button,.wood-fuhrer .wood-button,.wood-bieri .wood-button,.wood-zwei .wood-button{color:#17221e!important}.wood-bernhof .bern-side-label{color:#17221e}}
@media(prefers-reduced-motion:reduce){.wood *{scroll-behavior:auto!important;transition:none!important}}
`;

const renderers = { bernhof, fuhrer, bieri, schreinerzwei, 'fritschi-griesemer': fritschi };

export function render(lead) {
  const renderer = renderers[lead.slug];
  if (!renderer) throw new Error(`Unsupported wood lead: ${lead.slug}`);
  return { html: renderer(lead), css };
}
