"use client";
import {useState} from 'react';
import './concept.css';
import PolireMark from './mark';
import ConceptExperience, { ConceptMotion } from './concept-experience';
const data={
raum:{brand:'RAUM / ATELIER',tag:'ARCHITEKTUR & INTERIOR',title:'Raum für das Wesentliche.',intro:'Licht. Material. Proportion. Architektur, die nicht laut sein muss, um zu bleiben.',hero:'photo-1600585154340-be6161a56a0c',label:'Räume entdecken',section:'Drei Perspektiven. Eine Haltung.',cards:[['01 / WOHNEN','Villa am Hang','Offene Räume, warme Materialien und ein weiter Blick.','photo-1600210492486-724fe5c67fb0'],['02 / INTERIOR','Das stille Loft','Ein Zusammenspiel aus Licht, Holz und klaren Linien.','photo-1600607687920-4e2a09cf159d'],['03 / KONZEPT','Haus im Grünen','Innen und aussen als zusammenhängender Lebensraum.','photo-1600566753086-00f18fb6b3ea']],note:'Weniger Form. Mehr Gefühl.',body:'Ein Raum beginnt mit einer Frage: Wie möchten wir darin leben? Diese Studie erkundet ein Architekturstudio mit einer ruhigen, bildgetragenen digitalen Präsenz.'},
glanz:{brand:'GLANZWERK',tag:'AUTOMOTIVE DETAILING / KONZEPT',title:'Nicht nur sauber. Makellos.',intro:'Für alle, die ihr Fahrzeug nicht einfach fahren. Sondern lieben.',hero:'photo-1492144534655-ae79c964c9d7',label:'Finishes entdecken',section:'Jedes Detail zählt.',cards:[['01 / RESET','Interior Reset','Polster, Oberflächen und die Details dazwischen.','photo-1507136566006-cfc505b114fc'],['02 / REFLECT','Paint Correction','Ein Finish mit Tiefe. Eine Oberfläche ohne Ablenkung.','photo-1503376780353-7e6692767b70'],['03 / PROTECT','Ceramic Finish','Präzision bis zur letzten Schicht.','photo-1503736334956-4c8f8e92946d']],note:'Der Unterschied liegt im Finish.',body:'Von der ersten Inspektion bis zur letzten Kontrolle: Diese Designstudie zeigt, wie eine hochwertige Fahrzeugaufbereitung digital erlebbar wird.'},
tavola:{brand:'TAVOLA',tag:'CUCINA / VINO / CONVERSAZIONE',title:'Ein langer Abend. Ein guter Tisch.',intro:'Saisonale Küche, ein Glas Wein und Zeit füreinander. Willkommen an unserem Tisch.',hero:'photo-1517248135467-4c7edcad34c4',label:'Speisekarte ansehen',section:'Mit der Saison. Mit Gefühl.',cards:[['PER INIZIARE','Burrata & Tomate','Basilikum, reife Tomaten, Olivenöl · CHF 19','photo-1512621776951-a57141f2eefd'],['IL PIATTO','Pasta della casa','Hausgemachte Pasta, saisonales Gemüse · CHF 29','photo-1473093295043-cdd812d0e601'],['DOLCE','Ein süsser Abschluss','Tiramisù, Espresso, Kakao · CHF 12','photo-1571877227200-a0d98ea607e9']],note:'Gutes Essen bringt uns zusammen.',body:'Ein kleines Menü. Gute Zutaten. Und kein Grund, früh zu gehen. Eine fiktive Restaurantwelt – gestaltet für Vorfreude auf den nächsten gemeinsamen Abend.'}
};
const photo=(id)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=1800&q=85`;
export default function Concept({kind}){const d=data[kind];const [filter,setFilter]=useState('Alle');const [reveal,setReveal]=useState(50);const [done,setDone]=useState(false);return <main className={`concept concept-${kind}`}>
<ConceptMotion/><div className="concept-notice"><a className="concept-polire" href="/#work" aria-label="POLIRE – Zurück zu den Konzepten"><PolireMark/><strong>POLIRE</strong><span>Designkonzepte</span></a><span>Fiktive Marke · Designstudie · Kein reales Angebot</span></div>
<nav className="concept-nav"><a href="#top" className="concept-brand">{d.brand}</a><div><a href="#discover">{kind==='tavola'?'Menü':'Entdecken'}</a><a href="#story">Über uns</a><a href="#request">{kind==='tavola'?'Tisch anfragen':'Kontakt'}</a></div></nav>
<section className="concept-hero" id="top"><img sizes="100vw" srcSet={[480,800,1200,1800].map(w=>`${photo(d.hero).replace("w=1800",`w=${w}`)} ${w}w`).join(", ")} src={photo(d.hero)} alt={kind==='raum'?'Moderne Architektur mit grossen Fensterflächen':kind==='glanz'?'Sportwagen als Motiv der Fahrzeugpflege-Studie':'Warmer Restaurantinnenraum'} fetchPriority="high"/><div><p>{d.tag}</p><h1>{d.title}</h1><p className="concept-intro">{d.intro}</p><a className="concept-cta" href="#discover">{d.label}</a></div><span className="concept-edition">POLIRE STUDY / {kind==='raum'?'01':kind==='glanz'?'02':'03'}</span></section>
<div className="concept-ribbon" aria-hidden="true"><div>{Array.from({length:4},(_,i)=><span key={i}>{kind==='raum'?'LICHT / MATERIAL / PROPORTION':kind==='glanz'?'PRECISION / REFLECTION / OBSESSION':'BUON CIBO / BUON VINO / BELLA VITA'}<i>✳</i></span>)}</div></div><section className="concept-discover" id="discover"><header><p>ENTDECKEN / SELECTED</p><h2>{d.section}</h2></header>{kind==='raum'&&<div className="concept-filters">{['Alle','Wohnen','Interior','Konzept'].map(v=><button key={v} aria-pressed={filter===v} onClick={()=>setFilter(v)}>{v}</button>)}</div>}<div className="concept-cards">{d.cards.filter((_,i)=>filter==='Alle'||['Wohnen','Interior','Konzept'][i]===filter).map(([tag,title,body,img])=><article key={title}><div className="concept-image"><img loading="lazy" decoding="async" width="800" height="1000" sizes="(max-width: 760px) 88vw, 28vw" srcSet={[400,800,1200].map(w=>`${photo(img).replace("w=1800",`w=${w}`)} ${w}w`).join(", ")} src={photo(img)} alt={title}/></div><small>{tag}</small><h3>{title}</h3><p>{body}</p></article>)}</div></section>
{kind==='glanz'&&<section className="finish"><div><p>INTERAKTIVE FINISH-STUDIE</p><h2>Verschieben.<br/>Unterschied sehen.</h2><p>Eine stilisierte Bildsimulation – kein echter Vorher/Nachher-Nachweis.</p></div><div><div className="finish-image"><img src={photo(d.hero)} alt="Unverändertes Fahrzeugmotiv"/><img className="finish-dull" style={{clipPath:`inset(0 ${100-reveal}% 0 0)`}} src={photo(d.hero)} alt="Simulierte matte Oberfläche"/><i style={{left:`${reveal}%`}}/></div><label>Matt / Glanz<input aria-label="Finish vergleichen" type="range" min="0" max="100" value={reveal} onChange={e=>setReveal(e.target.value)}/></label></div></section>}
<ConceptExperience kind={kind}/><section className="concept-story" id="story"><p>UNSERE HALTUNG</p><h2>{d.note}</h2><p>{d.body}</p></section>
<section className="concept-request" id="request"><div><p>{kind==='tavola'?'EIN PLATZ AM TISCH':'DER NÄCHSTE SCHRITT'}</p><h2>{kind==='tavola'?'Bleiben Sie zum Essen.':'Eine Idee beginnt mit einem Gespräch.'}</h2><p>Interaktive Demo: Angaben werden nicht versendet oder gespeichert. Es entsteht keine Buchung.</p></div>{done?<div className="concept-receipt" role="status"><h3>So könnte Ihre Bestätigung aussehen.</h3><p>Demo abgeschlossen. Es wurde keine Anfrage versendet.</p><button onClick={()=>setDone(false)}>Demo erneut ansehen</button></div>:<form onSubmit={e=>{e.preventDefault();setDone(true)}}><label>Name<input required name="name" placeholder="Ihr Name"/></label>{kind==='tavola'?<><label>Datum<input required type="date"/></label><label>Personen<select defaultValue="2"><option>1</option><option>2</option><option>3</option><option>4</option><option>5</option><option>6</option></select></label></>:<label>Ihre Idee<textarea required rows="3" placeholder="Was haben Sie vor?"/></label>}<button type="submit">{kind==='tavola'?'Reservierung simulieren':'Anfrage simulieren'}</button></form>}</section>
<footer className="concept-footer"><strong>{d.brand}</strong><p>Ein Designkonzept von POLIRE. Bildmotive: Unsplash.</p><div className="concept-legal"><a href="/datenschutz">Datenschutz</a><a href="/impressum">Impressum</a></div><a href="/#contact">Eine eigene Website besprechen</a></footer></main>}
