export const enquiryCopy = {
  de: {
    otherDetails: 'Was meinen Sie damit? (optional)', otherPlaceholder: 'Beschreiben Sie kurz Ihre Idee oder was noch offen ist.',
    customBudget: 'Eigenes Budget', budgetDetails: 'Ihr Budget', budgetPlaceholder: 'Zum Beispiel CHF 1’500 oder CHF 100 pro Monat',
    asap: 'So schnell wie möglich', chooseDate: 'Datum selbst auswählen', startDate: 'Gewünschtes Startdatum',
    title: 'Erzählen Sie uns von Ihrem Projekt.',
    intro: 'Eine erste Idee reicht. Gemeinsam finden wir die passende Richtung.',
    details: '01 / Ihr Vorhaben', contact: '02 / Ihre Kontaktdaten',
    name: 'Ihr Name', company: 'Firma', email: 'E-Mail',
    service: 'Was brauchen Sie?', choose: 'Bitte auswählen',
    services: [['new', 'Eine neue Website'], ['redesign', 'Meine Website überarbeiten'], ['other', 'Etwas anderes / noch offen']],
    website: 'Bisherige Website', websiteHint: 'Falls Sie bereits eine Website haben, können Sie sie hier verlinken.',
    brief: 'Was wünschen Sie sich?', briefHint: 'Was soll Ihre Website können? Wie soll sie aussehen und wirken?',
    briefPlaceholder: 'Zum Beispiel: eine ruhige, moderne Website mit Terminbuchung …',
    examplesTitle: 'Websites, die Ihnen gefallen', examplesHint: 'Zeigen Sie uns gerne eine Richtung. Bis zu fünf Links sind möglich.',
    example: 'Beispiel-Website', addExample: 'Weiteres Beispiel hinzufügen', removeExample: 'Beispiel entfernen',
    inspiration: 'Was gefällt Ihnen an den Beispielen?', inspirationPlaceholder: 'Zum Beispiel die Farben, die Aufteilung oder die Bildsprache.',
    budget: 'Budgetrahmen', budgets: [['under-3000', 'Unter CHF 3’000'], ['3000-5000', 'CHF 3’000–5’000'], ['5000-10000', 'CHF 5’000–10’000'], ['over-10000', 'Über CHF 10’000']],
    timing: 'Gewünschter Start', timingPlaceholder: 'Zum Beispiel: November oder noch offen',
    optional: 'optional', open: 'Noch offen', required: 'Nur Name, E-Mail, Projektart und Ihre Wünsche sind erforderlich.',
    privacyBefore: 'Ihre Angaben werden über FormSubmit per E-Mail an POLIRE gesendet und zur Bearbeitung Ihrer Anfrage verwendet.', privacy: 'Datenschutzerklärung',
    submit: 'Anfrage senden', sending: 'Wird gesendet …', close: 'Formular schliessen',
    success: 'Vielen Dank für Ihre Anfrage.', successText: 'Ihre Anfrage wurde übermittelt. Wir melden uns in der Regel innerhalb von 1–2 Werktagen bei Ihnen.',
    done: 'Zurück zur Website', unavailable: 'Ihre Anfrage wurde nicht gesendet. Der Versand ist momentan nicht verfügbar. Bitte versuchen Sie es später erneut. Ihre Angaben bleiben in diesem Fenster erhalten.',
    error: 'Die Übermittlung konnte nicht bestätigt werden. Ihre Anfrage ist möglicherweise bereits angekommen. Bitte versuchen Sie es nicht sofort erneut. Ihre Angaben bleiben in diesem Fenster erhalten.',
    invalid: 'Bitte prüfen Sie Ihre Angaben und verwenden Sie für Links eine vollständige Webadresse.',
    limited: 'Zu viele Versuche in kurzer Zeit. Bitte warten Sie ein paar Minuten. Ihre Angaben bleiben erhalten.',
  },
  en: {
    otherDetails: 'What do you mean? (optional)', otherPlaceholder: 'Briefly describe your idea or what is still undecided.',
    customBudget: 'Custom budget', budgetDetails: 'Your budget', budgetPlaceholder: 'For example CHF 1,500 or CHF 100 per month',
    asap: 'As soon as possible', chooseDate: 'Choose a date', startDate: 'Preferred start date',
    title: 'Tell us about your project.',
    intro: 'An initial idea is enough. We will find the right direction together.',
    details: '01 / Your project', contact: '02 / Your contact details',
    name: 'Your name', company: 'Company', email: 'Email',
    service: 'What do you need?', choose: 'Please select',
    services: [['new', 'A new website'], ['redesign', 'A website redesign'], ['other', 'Something else / not sure yet']],
    website: 'Current website', websiteHint: 'If you already have a website, share its link here.',
    brief: 'What do you have in mind?', briefHint: 'What should your website do? How should it look and feel?',
    briefPlaceholder: 'For example: a calm, modern website with appointment booking …',
    examplesTitle: 'Websites you like', examplesHint: 'Show us a direction you like. You can add up to five links.',
    example: 'Example website', addExample: 'Add another example', removeExample: 'Remove example',
    inspiration: 'What do you like about the examples?', inspirationPlaceholder: 'For example the colours, layout or photography.',
    budget: 'Budget range', budgets: [['under-3000', 'Under CHF 3,000'], ['3000-5000', 'CHF 3,000–5,000'], ['5000-10000', 'CHF 5,000–10,000'], ['over-10000', 'Over CHF 10,000']],
    timing: 'Preferred start', timingPlaceholder: 'For example: November or still open',
    optional: 'optional', open: 'Still open', required: 'Only your name, email, project type and project description are required.',
    privacyBefore: 'Your details are sent to POLIRE by email via FormSubmit and used to respond to your enquiry.', privacy: 'Privacy notice',
    submit: 'Send enquiry', sending: 'Sending …', close: 'Close enquiry form',
    success: 'Thank you for your enquiry.', successText: 'Your enquiry has been submitted. We will usually reply within 1–2 business days.',
    done: 'Back to the website', unavailable: 'Your enquiry was not sent. Sending is currently unavailable. Please try again later. Your answers will stay in this window.',
    error: 'Delivery could not be confirmed. Your enquiry may already have arrived. Please do not retry immediately. Your answers will stay in this window.',
    invalid: 'Please check your details and use complete website addresses for links.',
    limited: 'Too many attempts in a short time. Please wait a few minutes. Your answers have been kept.',
  },
};
